- shippable.yml
In the nightly CI runs, the `centos8`, `opensuse15py2` and `opensuse15` targets always fail since no tests are run for them at all.
The obvious fix is to disable these targets. This improves the CI resource footprint of this repo as well :)
CI
> Disable all CI targets which do not run any tests

- plugins/modules/postgresql_set.py
postgresql_set: fix a boolean default
Backport of https://github.com/ansible-collections/community.general/pull/1343 so **no review needed**
`plugins/modules/postgresql_set.py`
> [Backport from community.general] postgresql_set: fix a boolean default

- plugins/modules/postgresql_query.py
- tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/31
postgresql_query: add explanation how to pass undefined variables as NULLs to positional_args
> postgresql_query: add explanation how to pass undefined variables as NULLs to positional_args

- plugins/modules/postgresql_user.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/35
`plugins/modules/postgresql_user.py`
> postgresql_user: add clarification about AWS password related nuances

- changelogs/fragments/37-postgresql_query_add_single_query_opt.yml
- plugins/modules/postgresql_query.py
- tests/integration/targets/postgresql_query/files/test0.sql
- tests/integration/targets/postgresql_query/files/test1.sql
- tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/34
Partial revert of https://github.com/ansible-collections/community.general/pull/886
postgresql_query: add `as_single_query` new option
`postgresql_query`
> postgresql_query: add as_single_query new option

- changelogs/fragments/43-modules_fix_version_parsing.yml
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_ping.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/40
```
>>> raw = 'PostgreSQL 11.6, compiled by Visual C++ build 1800, 64-bit'
>>> raw = raw.split()[1].split('.')
>>> raw
['11', '6,']
>>> int(raw[1].rstrip(','))
6
```
> postgresql_ping, postgresql_info: fix crash related to PgSQL version parsing

- galaxy.yml
Relates to https://8d4b759adbbe5195b96a-922c46b17cda87fc3b2e008fd8af57f8.ssl.cf1.rackcdn.com/51/3496099e4bd5c1f0cca6a158db1591e5035c3a99/third-party-check/ansible-galaxy-importer/ea0512c/job-output.html
```
2021-02-01 08:38:16.028465 | centos-8 | ERROR: The import failed for the following reason: Invalid collection metadata. Each author in 'authors' list must not be greater than 64 characters
```
galaxy.yml
> galaxy.yml: change authors field

- changelogs/fragments/51-postgresql_query_fix_datetime_timedelta_type_handling.yml
- plugins/modules/postgresql_query.py
- tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/47
> postgresql_query: fix datetime.timedelta type handling

- .azure-pipelines/azure-pipelines.yml
Exclude Fedora 31 from CI, add Fedora 33
> Exclude Fedora 31 from CI, add Fedora 33

- .azure-pipelines/azure-pipelines.yml
- changelogs/fragments/54-postgresql_query_add_warning_as_single_query.yml
- plugins/modules/postgresql_query.py
Related to https://github.com/ansible-collections/community.general/pull/886
Related Issues:
11:50 AM issue 1 https://github.com/ansible-collections/community.postgresql/issues/34
11:50 AM issue 2 https://github.com/ansible-collections/community.postgresql/issues/50
Introduction of query_all_results https://github.com/ansible-collections/community.general/pull/886
caused introduction of `as_single_query` option https://github.com/ansible-collections/community.postgresql/pull/37
To save backwards compatibility, the default value of the option was defined as `no`.
So, would be cool to notify users to set the option explicitly.
**the current behavior has NOT changed**
> postgresql_query: add warning to set as_single_query explicitly

- changelogs/fragments/68-postgresql_info_add_ret_values.yml
- plugins/modules/postgresql_info.py
- tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
The idea has initially appeared in https://github.com/ansible-collections/community.mysql/pull/115 , thank @rndmh3ro 
> postgresql_info: add full, raw, and patch ret version values

- changelogs/fragments/82-fix-fail-on-role.yml
- plugins/modules/postgresql_privs.py
This fixes the issue where the check is never reached because
the module is unconditionally exited, before, if the specified
role doesn't exist.
Which was effectively as if `fail_on_role` is always set to 'no'
plus the silencing of the warning. Which, of course, is quite a trap
and conflicts with the documentation, as well.
For symmetry and better troubleshooting that result now also includes
the executed queries (like the other call site).
How to reproduce the original issue: try to grant some privilege to a non-existing role.
```paste below
```
> Fix fail_on_role check

- changelogs/fragments/108-postgresql_db_directory_format.yml
- plugins/modules/postgresql_db.py
- tests/integration/targets/postgresql_db/tasks/main.yml
postgresql_db: add support for directory format
Fixes https://github.com/ansible-collections/community.postgresql/issues/83
`postgresql_db`
> postgresql_db: add support for directory format

- changelogs/fragments/107-postgresql_db_add_rename_state_value.yml
- plugins/modules/postgresql_db.py
- tests/integration/targets/postgresql_db/tasks/main.yml
- tests/integration/targets/postgresql_db/tasks/state_rename.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/100
postgresql_db: add the rename value to the state option
postgresql_db
> postgresql_db: add the rename value to the state option

- plugins/doc_fragments/postgres.py
It's easy to confuse `login_password` with `password` on in the postgresql_user module.
I have changed the wording to make it clearer that the  `login_user` and `login_password` variables are used by the module to establish a session.
community.postgresql.postgresql_user
`login_password` appears higher in the `community.postgresql.postgresql_user` documentation than `password` so it is an easy mistake to make.  In my case, the module executed without errors or warnings so this could save people time spent troubleshooting their authentication failures.
> Disambiguate login_user and login_password wording

- changelogs/fragments/138-postgresql_info_fix_ver_handling.yml
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_info.py
- tests/integration/targets/postgresql_ext/tasks/postgresql_ext_version_opt.yml
- tests/integration/targets/setup_postgresql_db/files/dummy--0.sql
- tests/integration/targets/setup_postgresql_db/tasks/main.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/137
Fixes https://github.com/ansible-collections/community.postgresql/issues/136
postgresql_info:
- fix crash when extension version is 0.
- add raw ret value for extensions
postgresql_ext (i put it in this PR because it needs for integration tests):
- fix extension of version 0 handling
plugins/modules/postgresql_ext.py
plugins/modules/postgresql_info.py
> postgresql_info: fix crash when extension version is 0.

- changelogs/fragments/134-postgresql_pg_hba-rule-specific-comments.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
Fixes #134
Currently, the module community.postgresql.postgresql_pg_hba would move those comments to the beginning of the file, which removes the comment-to-rule relation. To optionally preserve that and to optionally add such comments, I propose to introduce two new parameters to the module:
- _keep_comments_at_rules_ (bool, default=false)
- If true, comments that stand together with a rule in one line are kept behind that line.
- If false, such comments are moved to the beginning of the file, like all other comments.
- _comment_ (string, optional)
- A comment that will be placed in the same line behind the rule.
If not set, the behavior of the module remains like before.
postgresql_pg_hba
example use in a playbook:
```yaml
- name: manage pg_hba.conf …
```
> pg_hba.conf: add parameter to keep rule-specific comments next to the rule

- changelogs/fragments/120-postgresql_correct_server_version_check.yml
- plugins/modules/postgresql_slot.py
The check in postgresql_slot which determines if the PG server is 9.6+
has a typo in the version. It was using 96000 when the value should be
90600.
Also corrected the spelling in the comment that is part of said version
check.
Fixes #120
potgresql_slot
```
(postgres@[local]:5432/postgres[45017]) # show server_version_num ;
┌────────────────────┐
│ server_version_num │
├────────────────────┤
│ 90600              │
└────────────────────┘
(1 row)
```
As you can see, the correct version string is `90600` not `96000`
> correct version value in postgresql_slot

- .azure-pipelines/azure-pipelines.yml
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
Exclude some distributions from CI where PostgreSQL version is too old or where the same version is present in other distros
CentOS 6: `8.4.20` (excluded)
CentOS 7: `9.2.24`
CentOS 8: `10.17` (excluded)
Fedora 31 `11.8`(excluded)
Fedora 32 `12.6` (excluded)
Fedora 33 `12.7` (excluded)
Fedora 34 `13.4`
Ubuntu 16.04: `9.5` (excluded)
Ubuntu 18.04: `10.18` (excluded)
Ubuntu 20.04: `12.8`
RHEL 7.9: `9.2` (excluded)
RHEL 8.3: `10.17`
RHEL 8.4: `10.17`
After this PR we will test against:
- 9.2 (i think this is a good low border)
- 10
- 12
- 13
Testing
> Exclude some distributions from CI

- changelogs/fragments/drop_db_with_force.yml
- plugins/modules/postgresql_db.py
- tests/integration/targets/postgresql_db/tasks/main.yml
- tests/integration/targets/postgresql_db/tasks/manage_database.yml
- tests/integration/targets/postgresql_db/tasks/postgresql_db_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/109
Added a `force` (boolean) option with `state=absent`. Need to drop active connections first to be able to drop a database.
postgresql_db needs a force option with state=absent or it will fail to drop a database with active connections
1. When database does not exists, do nothing.
2. When database exists and has active connections, and force is True, it will drop the database
3. When database exists and has active connections, and force is False, it will fail to drop the database
4. When database exists and has no active connections, and force is False, it will drop the database
5. When database exists and has no active connections, and force is True, it will drop the database
```yaml …
```
> Need a force (bool) option for postgresql_db. Otherwise fails to drop a db with state=absent only

- plugins/module_utils/database.py
- plugins/modules/postgresql_privs.py
In issue #132 ( #133 ) it was reported that when there is an incorrect entry of the parameter `objs` ( or `obj`), it does not arise a more detail message about what is happening.
* plugin/modules/postgresql_privs.py
> postgresql_privs: Additional information when something goes wrong.

- README.md
- changelogs/fragments/163-better_handling_of_postgresql_extensions.yml
- plugins/modules/postgresql_ext.py
- tests/integration/targets/postgresql_ext/tasks/postgresql_ext_version_opt.yml
This PR is a bugfix and enhancement for better handling PostgreSQL extensions. The issues surrounding the current handling of extension versions are outlined in the related Issue #129.
Tried to keep it so that there is no change to the current interface or options that the user has to worry about with this update. Only change that the user may see is that a version of "latest" will now always ensure the latest version of an extension is installed whenever the play is run. It did not always do that in all cases before.
The module no longer cares about the actual "version number" of any extension since an extension version is a completely arbitrary string value. What determines which version is "greater" or "less than" another is simply the update paths that the extension author provides, …
> Better handling of extension versions

- changelogs/fragments/178-prepare_for_distutils_be_removed.yml
- plugins/module_utils/postgres.py
- plugins/module_utils/version.py
Prepare for distutils.version being removed in Python 3.12
Relates to https://github.com/ansible-collections/overview/issues/45#issuecomment-999911221
> Prepare for distutils.version being removed in Python 3.12

- changelogs/fragments/173-postgres_info_now_shows_the_info_of_each_specific_database.yml
- plugins/modules/postgresql_info.py
- tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
fixes #172
The reason `postgres_info.py` was gathering data on every database was because of a bug in `PgDbConn.reconnect()`, which is fixed here.
I also changed the main loop that iterate among all DBs to ignore DBs which it can't access because in AWS RDS not all DBs are accessible.
postgres_info.py
> bugfix: postgres_info.py now shows the info of each specific database

- changelogs/fragments/177-postgresql_ping_add_conn_err_msg_ret_val.yml
- plugins/module_utils/postgres.py
- plugins/modules/postgresql_copy.py
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_idx.py
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_lang.py
- plugins/modules/postgresql_membership.py
- plugins/modules/postgresql_owner.py
- plugins/modules/postgresql_ping.py
- plugins/modules/postgresql_publication.py
- plugins/modules/postgresql_query.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_sequence.py
- plugins/modules/postgresql_set.py
- plugins/modules/postgresql_slot.py
- plugins/modules/postgresql_subscription.py
- plugins/modules/postgresql_table.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- plugins/modules/postgresql_user_obj_stat_info.py
- tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml
- tests/unit/plugins/module_utils/test_postgres.py
Relates to https://github.com/ansible-collections/community.postgresql/issues/174
@tcraxs @ @klando @MichaelDBA @hunleyd @marcosdiez , needs your opinion on this:
1. Can this ret val be useful? I.e. to be able to use it inside playbooks (now we can see what's wrong only in warnings).
2. If you think this value is useful, should we return it always (i.e. as an empty string when the connection has succeeded) or only when an error occurres?
3. Any other thoughts?
@marcosdiez maybe we could use the related change in `connect_to_db` to fill up messages in https://github.com/ansible-collections/community.postgresql/pull/173
See the integration tests i added to `tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml` to see how it can be used.
```
- name: Try to connect to …
```
> postgresql_ping: return conn error message

- plugins/modules/postgresql_script.py
- tests/integration/targets/postgresql_script/aliases
- tests/integration/targets/postgresql_script/defaults/main.yml
- tests/integration/targets/postgresql_script/files/test0.sql
- tests/integration/targets/postgresql_script/files/test1.sql
- tests/integration/targets/postgresql_script/files/test10.sql
- tests/integration/targets/postgresql_script/files/test11.sql
- tests/integration/targets/postgresql_script/files/test12.sql
- tests/integration/targets/postgresql_script/files/test2.sql
- tests/integration/targets/postgresql_script/files/test3.sql
- tests/integration/targets/postgresql_script/files/test4.sql
- tests/integration/targets/postgresql_script/files/test5.sql
- tests/integration/targets/postgresql_script/files/test6.sql
- tests/integration/targets/postgresql_script/files/test7.sql
- tests/integration/targets/postgresql_script/files/test8.sql
- tests/integration/targets/postgresql_script/files/test9.sql
- tests/integration/targets/postgresql_script/meta/main.yml
- tests/integration/targets/postgresql_script/tasks/main.yml
- tests/integration/targets/postgresql_script/tasks/postgresql_script_initial.yml
postgresql_script: new module - Runs SQL statements from a file.
Relates to the discussion in https://github.com/ansible-collections/community.postgresql/issues/180#issuecomment-1032610020
The rough plan is:
In this PR:
After releasing
postgresql_script
> postgresql_script: new module

- changelogs/fragments/0-postgresql_query_fix.yml
- plugins/modules/postgresql_query.py
- tests/integration/targets/postgresql_query/files/test0.sql
- tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/180
I reproduced the bug in integration tests. After adding these changes, the tests have passed.
> postgresql_query: fix the module cannot handle files with \n at the end

- changelogs/fragments/1-postgresq_connection_fix.yml
- plugins/module_utils/postgres.py
- tests/unit/plugins/module_utils/test_postgres.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/194
The `database` conn param was deprecated as a keyword argument in favor of `dbname` since psycopg2 2.7.
> module_utils: get rid of deprecated alias database for conn param dbname when psycopg2 is 2.7+

- .github/patchback.yml
Add patchback bot
cc @hunleyd , to backport a PR to `stable-1`, we need to add the `backport-1` label to the PR. Similarly for following branches when they appear. If there's no corresponding label, feel free to create it.
> Add patchback bot

- .azure-pipelines/azure-pipelines.yml
- README.md
- tests/integration/targets/setup_postgresql_db/tasks/main.yml
Try to sidestep the pipeline error seen in #227 where the 'warn' arg to
the 'shell' module is claimed to be invalid by splitting the task into
a block/rescue using 'command' and 'yum' instead.
tests/integration/targets/setup_postgresql_db
> correct the pipeline error about 'warn'

- changelogs/fragments/0-postgresql_user_depraction_of_privs.yml
- plugins/modules/postgresql_user.py
Deprecate the `priv` argument of postgresql_user in favor of the postgresql_privs module
fixes #212
> deprecate 'priv' argument in postgresql_user

- changelogs/fragments/0-postgresql_user_depraction_of_privs.yml
- plugins/modules/postgresql_user.py
Fix the in-module markup for the documentation missed in #227
> fix: correct the markup in module documentation

- changelogs/fragments/0-postgresql_user_depraction_of_privs.yml
- plugins/modules/postgresql_user.py
backport of pr #227 (deprecate 'priv' argument in postgresql_user)
> [stable-1] backport of #227

- changelogs/fragments/issue_240_doc_change.yml
- plugins/modules/postgresql_owner.py
Update documentation to reflect what actually happens when `REASSIGNED OWNED BY` is invoked. 
`postgresql_owner`
> Documentation change for postgresql_owner.py 

- changelogs/fragments/285-postgresql_subscription_fix_idempontece.yml
- plugins/modules/postgresql_subscription.py
Fixes #280. `postgresql_subscription` module is not idempotent because the port is cast to `int`  in the following chunk of code( [335](https://github.com/ansible-collections/community.postgresql/blob/639197ead257c1b4c63627d035996790e904cf6e/plugins/modules/postgresql_subscription.py#L335)):
```py
try:
self.attrs['conninfo'][tmp[0]] = int(tmp[1])
except ValueError:
self.attrs['conninfo'][tmp[0]] = tmp[1]
```
On line [385](https://github.com/ansible-collections/community.postgresql/blob/639197ead257c1b4c63627d035996790e904cf6e/plugins/modules/postgresql_subscription.py#L385) the if condition always return false  because variable `connparams` is a dict of string
```py
if connparams != self.attrs['conninfo']:
changed = self.__set_conn_params(convert_conn_params(connparams), …
```
> fix: Cast connparams to allow idempotence (#280)

- plugins/modules/postgresql_user.py
Add comments to the existing examples that make use of the 'priv'
argument of the `postgresql_user` module. This was missed in #227
- Fix Pull Request
> mark deprecated examples

- changelogs/fragments/293-postgresql_membership_exact_value.yml
- plugins/module_utils/postgres.py
- plugins/modules/postgresql_membership.py
- tests/integration/targets/postgresql_membership/tasks/postgresql_membership_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/277
> postgresql_membership: add the exact state value to be able to specify a list of only groups a user must be a member of

- changelogs/fragments/308-postgresql_user_alter_statements_return.yml
- plugins/modules/postgresql_user.py
Fixes #307 by including "alter user" statements in the return value "queries".
> postgresql_user: include "alter user" statements in return value "queries"

- changelogs/fragments/303-postgresql_pg_hba_add_bulk_rule_arguments.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/tasks/main.yml
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_bulk_rules.yml
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
feature PR, fixes #297
A list of objects, specifying a rule for the pg_hba.conf. Each object can have the following keys (the "rule-specific arguments"), which are treated the same as if they were arguments of this module:
- `address`
- `comment`
- `contype`
- `databases`
- `method`
- `netmask`
- `options`
- `state`
- `users`
See `rules_behavior` for what happens when one of these keys missing in a `rules` item.
String, choices: `conflict` (default), `combine`.
When `conflict`, and `rules` is specified along with at least one normal rule-specific argument, the module fails. This should prevent accidental ambiguous operations. If a `rules` item is lacking some rule-specific argument, the respective module default is taken.
When `combine`, the normal rule-specific arguments are treated as …
> postgresql_pg_hba: bulk rule editing

- changelogs/fragments/316-postgresql_ping_fix_pg_version_parsing.yml
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_ping.py
Fixes `postgresql_ping` crashes parsing the yugabyte (aka yugabytedb) server version:
```
PostgreSQL 11.2-YB-2.15.1.0-b0 on x86_64-pc-linux-gnu, compiled by clang version 13.0.1 (https://github.com/yugabyte/llvm-project.git 191e3a05a55c8671bcc88d7387c04c55a4310500), 64-bit
```
Fixes #315
postgresql_ping
> fix: only parse the digits from the pg version (#315)

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml
- changelogs/fragments/285-postgresql_subscription_fix_idempontece.yml
- changelogs/fragments/308-postgresql_user_alter_statements_return.yml
- changelogs/fragments/316-postgresql_ping_fix_pg_version_parsing.yml
- changelogs/fragments/all_in_schema.yml
- changelogs/fragments/simplified-bsd-license.yml
- galaxy.yml
I ommited the changelog fragment `changelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml`.
> Release 1.7.5 commit

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml
- changelogs/fragments/285-postgresql_subscription_fix_idempontece.yml
- changelogs/fragments/293-postgresql_membership_exact_value.yml
- changelogs/fragments/303-postgresql_pg_hba_add_bulk_rule_arguments.yml
- changelogs/fragments/308-postgresql_user_alter_statements_return.yml
- changelogs/fragments/316-postgresql_ping_fix_pg_version_parsing.yml
- changelogs/fragments/all_in_schema.yml
- changelogs/fragments/simplified-bsd-license.yml
- galaxy.yml
I ommited the changelog fragment `changelogs/fragments/0-postgresql_user-deprecate-privs-manipulation.yml`.
to be merged *after* https://github.com/ansible-collections/community.postgresql/pull/319
> Release 2.2.0 commit

- plugins/modules/postgresql_user.py
Add a test to user_should_we_change_password to check if the password parameter is a SCRAM-256 hash, and if it is the same as the stored password.
This is a similar approach to when the provided password is a MD5 hash.
Fixes #301
community.postgresql.postgresql_user
> idempotent when password is scram hashed

- changelogs/fragments/329-postgresql_add_connect_params_field.yml
- plugins/doc_fragments/postgres.py
- plugins/module_utils/postgres.py
- plugins/modules/postgresql_query.py
- tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
- tests/integration/targets/postgresql_info/tasks/setup_publication.yml
- tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
- tests/unit/plugins/module_utils/test_postgres.py
Added "connect_params" parameter dict to allow any additional libpg connection parameters.
The postgres library "psycopg" used in this module allows to add
any parameters as kwargs.
The dict "connect_params" can be used to pass in any parameters as kwargs to "psycopg".
https://www.psycopg.org/docs/module.html#psycopg2.connect
This is a more generic approach of [PR#324](https://github.com/ansible-collections/community.postgresql/pull/324).
postgres_*
Affects all modules that establish a database connection.
The key/values of the connect_params parameter dict is passed unmodified as kwargs to the module.
For example:
There is a cluster setup "host1" and "host2". But we do not know which one
of the hosts is the primary (read-write access) and the secondary
(write-only …
> added connect_params to allow any additional parameters that libpg understands

- .azure-pipelines/azure-pipelines.yml
As per [21](https://github.com/ansible-collections/news-for-maintainers/issues/21) remove Fedora 35 from the Azure pipeline
- Testing Change Request
> test: remove f35 from azure pipeline

- .azure-pipelines/azure-pipelines.yml
Fedora 35 and older releases have been removed from Docker devel set of
tests. This patch sets Fedora to use release 36, which is the supported version.
See, https://github.com/ansible-collections/news-for-maintainers/issues/21
> CI: update Fedora to 36 in docker_devel tests

- changelogs/fragments/314-postgresql_info-quote-show-args.yml
- plugins/modules/postgresql_info.py
Co-authored-by: @Jhiliano
Modify postgresql_info to properly quote arguments to the `SHOW` command so that PG doesn't run it through the parser and complain about reserved keywords.
Fixes #314 
> fix(postgresql_info): properly quote args to SHOW to avoid triggering 'reserved word' errors

- changelogs/fragments/351-postgresql_pg_hba-add-connection-types.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/defaults/main.yml
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
Add `hostgssenc` and `hostnogssenc` (see https://www.postgresql.org/docs/current/auth-pg-hba-conf.html) to the list of supported connection types in pg_hba.conf.
fixes  issue #349
> postgresql_pg_hba: support connection types hostgssenc, hostnogssenc

- changelogs/fragments/332-postgresql_privs_def_privs_schemas.yml
- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/332
Fixes https://github.com/ansible-collections/community.postgresql/issues/333
Test task 332 executes the following queries:
```
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM \"ansible_db_user3\";
ALTER DEFAULT PRIVILEGES GRANT USAGE ON SCHEMAS TO \"ansible_db_user3\"
```
Test task 333 executes the following:
```
ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM \"ansible_db_user3\"
ALTER DEFAULT PRIVILEGES GRANT SELECT ON TABLES TO \"ansible_db_user3\"
```
Is it OK?
`not-specified` is introduced to preserve backwards compatibility, we can change it as a default in a later major release if needed.
> postgresql_privs: add support for alter default privileges grant usage on schemas

- requirements.txt
Adding a requirements.txt file for python dependencies. I noticed that `psycopg2-binary` is mentioned in the readme, but there's no requirements.txt. When using ansible-builder with this collection, the dependency is not automatically picked up when it could be if the file was there.
Please let me know if there needs to be some range limitations added.
Local testing with ansible-builder
```paste below
$ cp -a /home/jmighion/tmp/git/community.postgresql/ context/_build/
$ ansible-builder create
$ podman build -t test context/
...
[2/3] STEP 3/4: RUN ansible-builder introspect --sanitize --write-bindep=/tmp/src/bindep.txt --write-pip=/tmp/src/requirements.txt
---
python:
...
- 'psycopg2-binary  # from collection community.postgresql'
...
Successfully installed ... …
```
> Adding a requirements.txt file for python dependencies.

- changelogs/fragments/0-postgresql_privs.yml
- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/373
> postgresql_privs: fails with type=default_privs, privs=ALL, objs=ALL_DEFAULT

- changelogs/fragments/378-postgresql_pg_hba_fix_change_detection.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_bulk_rules.yml
fixes #376
- When parsing the `pg_hba.conf`, trim whitespace between the rule and comment in the same line, to ensure equality tests work.
- Determine whether something changed by checking if read and to-be-written rules differ. Previously the check was slightly different: When `overwrite` was enabled, the rule list was emptied and adding rules again counted as change.
> postgresql_pg_hba: fix false "changed" when called with "overwrite: true"

- changelogs/fragments/379-postgresql_privs.yml
- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/379
> postgresql_privs: raise an error when ALL_IN_SCHEMA is used with a value of the type parameter not in table, sequence, function or procedure

- changelogs/fragments/382-postgresql_privs_fix_schemas_with_special_names.yml
- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_privs/defaults/main.yml
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
fixes #381
Make postgresql_privs work with schema names containing arbitrary characters (e.g. `"` or `.`).
> postgresql_privs: fix schema quoting

- changelogs/fragments/0-postgresql_set_avoid_wrong_values.yml
- plugins/modules/postgresql_set.py
- tests/integration/targets/postgresql_set/tasks/options_coverage.yml
The PR #357 fix the multi-value parameters management (issue #78), but the new check assumes as multi-value each parameter with a comma in the value, that is incorrect as there are single-value parameters with comma in value.
If a single-value parameter is treated as a multi-value, the 'param_set' function builds an ALTER SYSTEM SET command with multiple comma-separated values, that fails with the message:
```
ERROR:  SET log_line_prefix takes only one argument
```
Single-value parameters with possible comma in value are  "*_command" and "*_prefix" that for exmple in v12 are:
- ssl_passphrase_command
- archive_command
- restore_command
- archive_cleanup_command
- recovery_end_command
- log_line_prefix
The most critical (that I add in tests) is 'log_line_prefix' because often it contains …
> Fix postgresql_set module if single-value param contains comma in value

- changelogs/fragments/399-missing-import.yml
- plugins/module_utils/postgres.py
On some of our systems the `postgresql_query` task failed with the following error:
AttributeError: module 'psycopg2' has no attribute 'extras'
Applying the patch from this commit fixed the issue for me on those systems. This was previously reported in issue #283. However now that some time has passed, I am unable to reproduce the issue on our newer systems.
In any case, this is still a mistake that could cause problems in the future, so I think it would be better to fix it.
The reason that this mistake is not causing any actual errors in normal situations is because of how the python import system functions: All of the entrypoints (all the source files under plugins/modules) have an import for `psycopg2.extras`. This causes `extras` to be available on `psycopg2` for any code (in any …
> Add missing psycopg2.extras import

- changelogs/fragments/1-postgresql_privs_deprecate_password.yml
- plugins/doc_fragments/postgres.py
- plugins/module_utils/postgres.py
- plugins/modules/postgresql_privs.py
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.12.txt
- tests/sanity/ignore-2.13.txt
- tests/sanity/ignore-2.14.txt
- tests/sanity/ignore-2.15.txt
- tests/unit/plugins/module_utils/test_postgres.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/406
Note: we can't add an alias for `password` as it's a valid separate parameter in `postgresql_user`.
We should probably deprecate and remove those aliases in 4.0.0 but in another PR
> postgresql_privs: deprecate password argument in favor of login_password

- changelogs/fragments/0-postgres.yml
- plugins/module_utils/postgres.py
- tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml
- tests/unit/plugins/module_utils/test_postgres.py
SUMMARY
Added search for PGPORT and PGUSER environment variables
If there are environment variables, and the port and user are not specified, then the value PGPORT and PGUSER is assigned
In other cases, default values or explicitly specified values are assigned
issue #311 
ISSUE TYPE
Feature Pull Request
> Added search for PGPORT and PGUSER environment variables

- meta/runtime.yml
Fixes #313
Adds possibility to set `module_defaults` for calling modules with same arguments, e.g. `login_user` and `login_password` as described in [https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html](https://docs.ansible.com/ansible/latest/user_guide/playbooks_module_defaults.html).
`meta/runtime.yml`
This change adds the Module defaults group `all`, which allows setting common arguments.
For example, these tasks both need to define `login_user` and `login_password` for successful connection:
```yaml
- name: Create a new database with name "acme"
community.postgresql.postgresql_db:
login_user: test
login_password: test
name: acme
- name: Add a comment on django user
community.postgresql.postgresql_user:
login_user: test …
```
> Added action_group all for module_defaults.

- changelogs/fragments/428-postgres_info_support_non_numeric_extenstion_version.yml
- plugins/modules/postgresql_info.py
- tests/integration/targets/postgresql_ext/tasks/postgresql_ext_version_opt.yml
- tests/integration/targets/setup_postgresql_db/files/dummy--3-1.0-1.sql
- tests/integration/targets/setup_postgresql_db/files/dummy--3-1.0.sql
- tests/integration/targets/setup_postgresql_db/files/dummy--3-1.foo.sql
- tests/integration/targets/setup_postgresql_db/files/dummy--3.0-1.sql
- tests/integration/targets/setup_postgresql_db/files/dummy--3.0-foo.sql
- tests/integration/targets/setup_postgresql_db/files/dummy--3.beta.sql
- tests/integration/targets/setup_postgresql_db/files/dummy--4.0.sql
- tests/integration/targets/setup_postgresql_db/files/dummy--v4.sql
- tests/integration/targets/setup_postgresql_db/files/dummy.control
- tests/integration/targets/setup_postgresql_db/tasks/main.yml
- add regex check that find out if extension version is numeric e.g. 1.0 , 1.0.1 or 1.1-1
- get first part of minor if it is split in to parts like this: '4-1'
- also set major to None if extension version is not numeric.
Fixes [#425](https://github.com/ansible-collections/community.postgresql/issues/425)
>  add support for non numeric extenstion version

- changelogs/fragments/430-action_group_all_for_module_defaults.yml
Added missing changelog fragment for already merged PR #430.
changelogs/fragments/430-action_group_all_for_module_defaults.yml
As it affects the whole collection (with non-breaking behavior) I ommited the scope.
> Added missing changelog fragment for PR #430.

- changelogs/fragments/0-postgresql_user.yml
- plugins/modules/postgresql_user.py
This PR for ISSUE https://github.com/ansible-collections/community.postgresql/issues/431
We have to remove the check "if changed" at the end of the code before rollback or commit because we anyway open a transaction and at the end ought to close it. (but this is not a big problem and we still can hold it in code if folks want it :) 
It's not from just a theoretical part, I tested and saw transactions "in idle in transaction" status as well :)
> postgresql_user: fix db closing

- changelogs/fragments/0-postgresql_info.yml
- plugins/modules/postgresql_info.py
When an unprivileged user received a subscription, an error occurred: permission denied for table pg_subscription.
Now a check has been added, by getting the available columns and displaying only them.
Solution of the issue: #429 
Feature Pull Request
> Added checking of available columns when receiving a subscription from the database

- tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
- tests/integration/targets/setup_postgresql_replication/defaults/main.yml
- tests/integration/targets/setup_postgresql_replication/handlers/main.yml
- tests/integration/targets/setup_postgresql_replication/tasks/setup_postgresql_cluster.yml
Fix CI tests, postgresql_info and _subscription integration tests now use PostgreSQL 15
There were several issues:
- mess with package installation. From now on `_info` and `_subscription` (which use this target) will run against PG 15
- postgresql_info tasks using a wrong port (default)
- main reason why servers hung indefinitely were ..logs. After I added `pg_ctl start .. -l <personal_log_file>` to each launch task, it will run
If other maintainers are OK, after merging and backporting, please relaunch tests in https://github.com/ansible-collections/community.postgresql/pull/444 and merge-backport it if green
> Fix CI tests, postgresql_info and _subscription integration tests now use PostgreSQL 15

- changelogs/fragments/451-postgresql_privs_fix_connect_params_being_ignored.yml
- plugins/modules/postgresql_privs.py
Fixes #450
Where connect_params were ignored for community.postgresql.postgresql_privs
Previous connect_params were ignored. A helper method used in postgresql_user took care of this and other checking which was being done here, including unix socket check. 
The end result is connect_params being properly honored now.
connect_params with:
```
connect_params:
sslcert: "{{ db_cert }}"
sslkey: "{{ db_key }}"
sslrootcert: "{{ db_ca }}"
```
Before: (fails with cert error, same cert error I get if I leave out connect_params entirely)
```
failed: [foo -> 127.0.0.1] (item={'privs': 'ALL', 'objs': 'tables', 'type': 'default_privs'}) => {"ansible_loop_var": "privilege", "changed": false, "msg": "Could not connect to database: connection to server at …
```
> Fix connect_params being ignored on postgresql_privs

- changelogs/fragments/451-postgresql_privs_fix_connect_params_being_ignored.yml
- plugins/modules/postgresql_privs.py
(cherry picked from commit bbb325758ec4cba98e731a3d72dace3c3b3ac2d3)
This is a backport of the changes in #451 resolving a conflict in `postgresql_privs.py`
Previous connect_params were ignored. A helper method used in postgresql_user took care of this and other checking which was being done here, including unix socket check. 
The end result is connect_params being properly honored now.
connect_params with:
```
connect_params:
sslcert: "{{ db_cert }}"
sslkey: "{{ db_key }}"
sslrootcert: "{{ db_ca }}"
```
Before: (fails with cert error, same cert error I get if I leave out connect_params entirely)
```
failed: [foo -> 127.0.0.1] (item={'privs': 'ALL', 'objs': 'tables', 'type': 'default_privs'}) => {"ansible_loop_var": "privilege", "changed": false, …
```
> [PR #451/bbb32575 backport][stable-1] Fix connect_params being ignored (#451)

- changelogs/fragments/0-postgresql_privs.yml
- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_user/tasks/main.yml
Relates to https://github.com/ansible-collections/community.postgresql/pull/451
and https://github.com/ansible-collections/community.postgresql/pull/462
> postgresql_privs: fix breaking changes related to password argument

- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
- tests/integration/targets/postgresql_user/tasks/postgresql_user_initial.yml
Due to a change in the receipt of connection parameters in postgresql_privs ( #451 ), fixed the integration tests.
> Fixed integration tests

- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
- tests/integration/targets/postgresql_user/tasks/postgresql_user_initial.yml
Due to a change in the receipt of connection parameters in postgresql_privs ( https://github.com/ansible-collections/community.postgresql/pull/451 ), fixed the integration tests.
> [PR #462/8dbc629 backport][stable-1] Fixed integration tests

- plugins/doc_fragments/postgres.py
- plugins/modules/postgresql_ext.py
Fixes #476 
Removing duplicate Notes from postgresql_ext module documentation.
Adding highlights to doc_fragments to make the look consistent.
postgresql_ext
https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_ext_module.html#notes
> Duplicates in Notes for postgresql_ext

- plugins/doc_fragments/postgres.py
- plugins/modules/postgresql_copy.py
- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_idx.py
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_lang.py
- plugins/modules/postgresql_membership.py
- plugins/modules/postgresql_owner.py
- plugins/modules/postgresql_pg_hba.py
- plugins/modules/postgresql_ping.py
- plugins/modules/postgresql_privs.py
- plugins/modules/postgresql_publication.py
- plugins/modules/postgresql_query.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_script.py
- plugins/modules/postgresql_sequence.py
- plugins/modules/postgresql_set.py
- plugins/modules/postgresql_slot.py
- plugins/modules/postgresql_subscription.py
- plugins/modules/postgresql_table.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- plugins/modules/postgresql_user_obj_stat_info.py
Moved all `check_mode` notes in `DOCUMENTATION` to the `attributes:` section.
Fixes #435
All modules documentation
Most modules have full support for the `check_mode`, with few exceptions:
* postgresql_script doesn't support the check_mode
* postgresql_tablespace has partial support
* not sure whether postgresql_copy should be marked as `full` or `partial`, any feedback welcome
postgresql_pg_hba also supports the `diff_mode`, so that was also added to the attributes section for this module. The pg_hba module isn't sharing the postgres.py doc fragment, so its documentation structure is different from the rest.
> Doc attributes

- changelogs/fragments/4-postgresql_user.yml
- plugins/modules/postgresql_user.py
Relates to https://github.com/ansible-collections/community.postgresql/issues/493
> postgresql_user: move the deprecated privs argument removal to 4.0.0

- changelogs/fragments/5-postgresql_pg_hba.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
postgresql_pg_hba: remove deprecated order argument
> postgresql_pg_hba: remove deprecated order argument

- plugins/module_utils/postgres.py
Instead of a using a ternary operator we rely on get function to define the default value for the PostgreSQL port.
None, just a small and minor change.
Rely on python method envinron.get to define the default value for th postgresql port.
> Use get properties to define default port for PG

- changelogs/fragments/505-postgresql_set.yml
- plugins/modules/postgresql_set.py
My PR fixes an error message in postgresql_set and adds a missing comment (both in param_set function).
postgresql_set
Error in param_set is "Unable to **get** ..." but must be "Unable to **set** ...".
Comment is missed from PR #400.
> postgresql_set - fixed error message in param_set function

- changelogs/fragments/504_postgresql_ext.yml
- plugins/modules/postgresql_ext.py
- tests/integration/targets/postgresql_ext/tasks/postgresql_ext_version_opt.yml
Actually postgresql_ext module always results changed if version=latest.
When latest extension version is installed, every update command has no effect:
```
test=# SELECT name, default_version, installed_version FROM pg_catalog.pg_available_extensions WHERE name = 'adminpack';
name    | default_version | installed_version
-----------+-----------------+-------------------
adminpack | 2.1             |
(1 row)
test=# CREATE EXTENSION adminpack VERSION '1.0';
CREATE EXTENSION
test=# SELECT name, default_version, installed_version FROM pg_catalog.pg_available_extensions WHERE name = 'adminpack';
name    | default_version | installed_version
-----------+-----------------+-------------------
adminpack | 2.1             | 1.0
(1 row)
test=# ALTER EXTENSION adminpack UPDATE TO '2.0';
ALTER …
```
> postgresql_ext - Added idempotence when version=latest

- README.md
Updated list of tested Postgres versions
Fixes #509
README
Small update to the list of tested OS and PG versions.
Among other things we test against many versions of RHEL 8 - 8.3, 8.4, 8.5, 8.6, 8.7 - probably not necessary to list them all.
> Updated list of tested versions

- .azure-pipelines/azure-pipelines.yml
- README.md
- tests/integration/targets/setup_postgresql_db/defaults/main.yml
- tests/integration/targets/setup_postgresql_db/tasks/main.yml
- tests/integration/targets/setup_postgresql_db/vars/Ubuntu-20-py3.yml
- tests/integration/targets/setup_postgresql_db/vars/Ubuntu-22-py3.yml
Added a new test target with Ubuntu 2204 and Psycopg 3.
The test environment
Only one new test target for now, to enable automated testing of modules modified to work with the new Psycopg 3 in #499
This PR doesn't touch the collection functionality, it only updates the test environment.
Also updated the test container as per https://github.com/ansible-collections/news-for-maintainers/issues/49
And updated the Remote devel RHEL test to use RHEL 8.8
> Added test target Ubuntu 2204 with Psycopg 3

- changelogs/fragments/518-psycopg-server_version.yml
- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_privs.py
- plugins/modules/postgresql_publication.py
- plugins/modules/postgresql_set.py
- plugins/modules/postgresql_slot.py
- plugins/modules/postgresql_subscription.py
Psycopg version 2 and 3 provide the database server version slightly differently.
This PR takes advantage of existing get_server_version function which already handles the Psycopg functionality change.
It will help with https://github.com/ansible-collections/community.postgresql/issues/499.
No functionality change
Several modules
See get_server_version at https://github.com/ansible-collections/community.postgresql/blob/main/plugins/module_utils/postgres.py#L466
> Psycopg and server version

- changelogs/fragments/522-psycopg-cursor_args.yml
- plugins/module_utils/postgres.py
- plugins/modules/postgresql_copy.py
- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_idx.py
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_lang.py
- plugins/modules/postgresql_membership.py
- plugins/modules/postgresql_owner.py
- plugins/modules/postgresql_ping.py
- plugins/modules/postgresql_privs.py
- plugins/modules/postgresql_publication.py
- plugins/modules/postgresql_query.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_script.py
- plugins/modules/postgresql_sequence.py
- plugins/modules/postgresql_set.py
- plugins/modules/postgresql_slot.py
- plugins/modules/postgresql_subscription.py
- plugins/modules/postgresql_table.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- plugins/modules/postgresql_user_obj_stat_info.py
Moved psycopg cursor arguments to the common postgres.py. 
This will help with #499, when we decide to add Psycopg 3 support most modules won't need any changes.
All modules
This PR is based on #517 where these changes are tested with both Psycopg 2 and 3.
> Common cursor arguments

- changelogs/fragments/-postgresql_set.yml
- changelogs/fragments/521-postgresql_set.yml
- plugins/modules/postgresql_set.py
- tests/integration/targets/postgresql_set/tasks/options_coverage.yml
- tests/integration/targets/setup_postgresql_db/tasks/main.yml
- tests/integration/targets/setup_postgresql_db/vars/RedHat-py3.yml
- tests/integration/targets/setup_postgresql_db/vars/RedHat.yml
My PR fixes *GUC_LIST_QUOTE* parameters management in *postgresql_set* module.
*GUC_LIST_QUOTE* parameters are multi-value parameters (like *GUC_LIST_INPUT* parameters) whose elements are surrounded by double-quotes if not match `^[A-Za-z09_]+$` pattern.
Now such double-quotes are ignored by *postgresql_set* module and it causes an always-changed status in these cases. It is a **very serious bug** if the parameter is a *postmaster*, as *unix_socket_directories* (it became *GUC_LIST_QUOTE* in PostgreSQL 14).
The bug has not seen until now as *GUC_LIST_QUOTE* parameters are few and many of them have not valid values that contain special characters (as *shared_preload_libraries* parameter).
Examples:
```
pg13=# ALTER SYSTEM SET unix_socket_directories = '/var/run/postgresql';
ALTER SYSTEM …
```
> postgresql_set - Fix GUC_LIST_QUOTE parameters

- .azure-pipelines/azure-pipelines.yml
- README.md
- tests/integration/targets/setup_postgresql_db/vars/Fedora-38-py3.yml
Added Fedora 38 test target
New test target
Fedora 38 comes with psycopg2 and psycopg3.1 packages, and we install both.
Current testing will use the psycopg2 library. 
When we add Psycopg 3 support the psycopg3 library will get used.
> Fedora 38 test target

- plugins/modules/postgresql_user_obj_stat_info.py
- tests/integration/targets/setup_postgresql_db/vars/Fedora-38-py3.yml
Fixed the Fedora 38 test build.
Plus more psycopg related refactoring to help with #499
* postgresql_user_obj_stat_info
* Fedora 38 tests
The `exec_sql` function in postgresql_user_obj_stat_info doesn't work when psycopg3 is used, passing an undefined parameter.
It has been fixed by only passing the parameter when it is needed.
> Psycopg refactor and Fedora 38 test fix

- tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
- tests/integration/targets/postgresql_script/tasks/postgresql_script_initial.yml
- tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml
Modified existing tests to work with Psycopg 3 and added extra Psycopg related tests.
The postgresql_user module handles the "database is read only" error, although only when altering a user. Tests were added to verify the behaviour.
Tests were added to verify the path in postgresql_query when `encoding` is specified.
`query_result` should be a list. When the list is empty, currently using psycopg2 we return an empty dict. When psycopg3 is used the same code will return an empty list. I think it is OK to keep the current behaviour, but no need to preserve that for psycopg3.
- Additional tests
Test harness
```paste below
```
> Additional Psycopg tests

- changelogs/fragments/_fix_ret_vals_doc.yml
- plugins/modules/postgresql_copy.py
- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_idx.py
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_lang.py
- plugins/modules/postgresql_membership.py
- plugins/modules/postgresql_owner.py
- plugins/modules/postgresql_pg_hba.py
- plugins/modules/postgresql_ping.py
- plugins/modules/postgresql_privs.py
- plugins/modules/postgresql_publication.py
- plugins/modules/postgresql_query.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_sequence.py
- plugins/modules/postgresql_set.py
- plugins/modules/postgresql_slot.py
- plugins/modules/postgresql_subscription.py
- plugins/modules/postgresql_table.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- plugins/modules/postgresql_user_obj_stat_info.py
This is a backport of PR https://github.com/ansible-collections/community.postgresql/pull/546 as merged into main (https://github.com/ansible-collections/community.postgresql/commit/6a5ddbf13c9a120da0b1142e044519bd2ecf10d0).
In all modules returned values are described in documentation as `always` returned, but really they are returned only at modules `success`.
With my PR I fixed all modules documentation, replacing `always` with `success` when present.
Other bugfixes:
- removed `changed` when used with `success` (no sense)
- replaced `on success` with `success` when used
> [PR #546/6a5ddbf backport][stable-1] fixed 'returned' value of all returned values of all modules

- changelogs/fragments/_fix_ret_vals_doc.yml
- plugins/modules/postgresql_copy.py
- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_idx.py
- plugins/modules/postgresql_info.py
- plugins/modules/postgresql_lang.py
- plugins/modules/postgresql_membership.py
- plugins/modules/postgresql_owner.py
- plugins/modules/postgresql_pg_hba.py
- plugins/modules/postgresql_ping.py
- plugins/modules/postgresql_privs.py
- plugins/modules/postgresql_publication.py
- plugins/modules/postgresql_query.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_script.py
- plugins/modules/postgresql_sequence.py
- plugins/modules/postgresql_set.py
- plugins/modules/postgresql_slot.py
- plugins/modules/postgresql_subscription.py
- plugins/modules/postgresql_table.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- plugins/modules/postgresql_user_obj_stat_info.py
This is a backport of PR https://github.com/ansible-collections/community.postgresql/pull/546 as merged into main (https://github.com/ansible-collections/community.postgresql/commit/6a5ddbf13c9a120da0b1142e044519bd2ecf10d0).
In all modules returned values are described in documentation as `always` returned, but really they are returned only at modules `success`.
With my PR I fixed all modules documentation, replacing `always` with `success` when present.
Other bugfixes:
- removed `changed` when used with `success` (no sense)
- replaced `on success` with `success` when used
> [PR #546/6a5ddbf backport][stable-2] fixed 'returned' value of all returned values of all modules

- plugins/modules/postgresql_ext.py
This is a backport of an PR #545 extract, to only fix ext module return parameter 'query' name in documentation.
> [PR #545/extract backport][stable-1] fixed ext module return parameter 'query' name in documentation

- plugins/modules/postgresql_ext.py
This is a backport of an PR #545 extract, to only fix ext module return parameter 'query' name in documentation.
> [PR #545/extract backport][stable-2] fixed ext module return parameter 'query' name in documentation

- README.md
- changelogs/fragments/556_psycopg251.yml
- changelogs/fragments/556_psycopg28.yml
- plugins/doc_fragments/postgres.py
- plugins/module_utils/postgres.py
- plugins/modules/postgresql_user.py
- tests/unit/plugins/module_utils/test_postgres.py
Updated the code to clarify that Psycopg versions older than 2.5.1 aren't fully supported.
New versions of psycopg2 use the same logic as psycopg 3, and de-supporting older versions of psycopg2 will allow us to simplify the code where it has to work with both versions for #499 
- Docs Pull Request and refactoring
Documentation and postgresql_user
Initially this PR was created to make 2.8 the minimum version, but then realised that we still use/test on 2.7.5 in RHEL 8 and 2.5.1 in CentOS 7.
> Psycopg 2.5.1 minimum

- README.md
As per the request on Matrix, add some forum links to the README. A minor tweak here and there for formatting as well. You can see the rendered version of these changes [here](https://github.com/hunleyd/community.postgresql/blob/main/README.md)
> update readme w/ forum links

- .codespell-exclude-file
- .codespellrc
- .pre-commit-config.yaml
- CHANGELOG.rst
- CONTRIBUTING.md
- changelogs/changelog.yaml
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
- tests/integration/targets/postgresql_user_obj_stat_info/tasks/postgresql_user_obj_stat_info.yml
- tests/unit/plugins/module_utils/test_postgres.py
- tox.ini
Add some `pre-commit` configuration to enforce usage of linter, `autoflake`, `flake8` and `codespell` .
> Add pre-commit configuration

- changelogs/fragments/585-decode-data-from-sql_ascii-databases.yml
- plugins/modules/postgresql_user.py
- tests/integration/targets/postgresql_user/defaults/main.yml
- tests/integration/targets/postgresql_user/tasks/main.yml
- tests/integration/targets/postgresql_user/tasks/postgresql_user_sql_ascii_db.yml
- tests/integration/targets/setup_postgresql_db/defaults/main.yml
- tests/integration/targets/setup_postgresql_db/tasks/main.yml
- tests/integration/targets/setup_postgresql_db/tasks/sql_ascii.yml
Hello!
This PR fixes #584, however, I'm not sure if it's the only code that interacts with potentially encoded bytes.
Some other options are to:
- Do something like https://github.com/psycopg/psycopg/commit/ca6db5c213ad61af1f4690339248a3a447b31ef5
- https://github.com/psycopg/psycopg/issues/503
- https://github.com/psycopg/psycopg/issues/561
- Set a default connection parameter `client_encoding: utf8` in `postgres_common_argument_spec`
`postgres_user`
> Decode bytes object from sql_ascii databases

- tests/sanity/ignore-2.17.txt
Ignore sanity failings
Spotted the red shield in README
if i change `type` to `isinstance`, it fails with another error that the second type is not valid, so let's ignore it as it's just "not idiomatic".
> Ignore sanity errors

- .azure-pipelines/azure-pipelines.yml
As per https://github.com/ansible-collections/news-for-maintainers/issues/63, bump Fedora 38 to 39 for Azure pipeline
> ci(azure): bump fedora to 39

- .azure-pipelines/azure-pipelines.yml
- README.md
AZP: remove Fedora 36, update README test matrix
- Tests against Fedora 36 have been failing for a week because of their repo issues. Removing it as we already test against Postgres 14 and same connector version 2.9.1 in the other targets
- Removing Fedora 34 as it's absent in AZP
- Updated Fedora 38 connector version to the actual one. Probably was a copy-paste error
> AZP: remove Fedora 36, update README test matrix

- .azure-pipelines/azure-pipelines.yml
- README.md
Manual backport of https://github.com/ansible-collections/community.postgresql/pull/628
> [stable-1] AZP: remove Fedora 36, update README test matrix

- .azure-pipelines/azure-pipelines.yml
- README.md
Manual backport of https://github.com/ansible-collections/community.postgresql/pull/628
> [stable-2] AZP: remove Fedora 36, update README test matrix

- .azure-pipelines/azure-pipelines.yml
- README.md
- tests/integration/targets/postgresql_owner/tasks/postgresql_owner_initial.yml
Removing stable-2.13 as EOL, see the [matrix](https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix)
Needs backport to stable-1 and stable-2
> AZP: remove testing against stable-2.13 as EOL

- changelogs/fragments/0-postgresql_db.yml
- plugins/modules/postgresql_db.py
- tests/integration/targets/postgresql_db/tasks/main.yml
- tests/integration/targets/postgresql_db/tasks/postgresql_db_comment.yml
Relates to https://github.com/ansible-collections/community.postgresql/issues/614
Adds the comment argument to the postgresql_db module
> postgresql_db: add comment feature

- changelogs/fragments/4-postgresql_ext.yml
- plugins/module_utils/postgres.py
- plugins/modules/postgresql_ext.py
- tests/integration/targets/postgresql_ext/tasks/postgresql_ext_initial.yml
relates to https://github.com/ansible-collections/community.postgresql/issues/354
> postgresql_ext: add comment argument

- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- tests/integration/targets/postgresql_db/tasks/postgresql_db_comment.yml
Forget to do it while implementing the comment argument feature.
Note: Not adding this to every module's tests as the function used is the same. In case it changes, the whole set of test targets will be triggered anyway, so having `trust_input: false` only in one target is imo enough.
> postgresql_db,_schema,_tablespace,_user: add comment value to check_input function

- changelogs/fragments/5-postgresql_publication.yml
- plugins/modules/postgresql_publication.py
- tests/integration/targets/postgresql_publication/tasks/postgresql_publication_initial.yml
> postgresql_publication: add comment argument

- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- tests/integration/targets/postgresql_db/tasks/postgresql_db_comment.yml
- tests/integration/targets/postgresql_ext/tasks/postgresql_ext_initial.yml
- tests/integration/targets/postgresql_schema/tasks/postgresql_schema_initial.yml
- tests/integration/targets/postgresql_tablespace/tasks/postgresql_tablespace_initial.yml
- tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml
Fixes a wrong behavior when you reset a comment by passing `comment: ''` which leads to always executing the `COMMENT ON OBJECT_TYPE "obj_name" IS ''`.
No fragments are needed as the feature hasn't been released.
> modules: fix reset comment

- plugins/module_utils/postgres.py
- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_ext.py
- plugins/modules/postgresql_publication.py
- plugins/modules/postgresql_schema.py
- plugins/modules/postgresql_subscription.py
- plugins/modules/postgresql_tablespace.py
- plugins/modules/postgresql_user.py
- tests/integration/targets/postgresql_ext/tasks/postgresql_ext_initial.yml
- tests/integration/targets/postgresql_publication/tasks/postgresql_publication_initial.yml
- tests/integration/targets/postgresql_subscription/tasks/postgresql_subscription_initial.yml
- tests/integration/targets/postgresql_tablespace/tasks/postgresql_tablespace_initial.yml
- tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml
- W/o this change, it doesn't return the `COMMENT ON ..` query in executed queries in check mode
- This PR doesn't touch modules that does not return queries in check mode. If we want this, we should implement it separately
- Fragments are not needed
> Fix queries handling for comment feature

- tests/utils/shippable/shippable.sh
Sanity tests: fix SC2153 error spotted by scheduled CI runs
> Sanity tests: fix SC2153 error

- .azure-pipelines/azure-pipelines.yml
- README.md
- tests/sanity/ignore-2.18.txt
As stable-2.18 has been recently branched, add testing against stable-2.17
> AZP: add testing against stable-2.17

- changelogs/fragments/690-revoke-functions-from-user.yaml
- plugins/modules/postgresql_privs.py
This PR enables ability to revoke functions from user with community.postgresql.postgresql_privs.
Fixes #687.
module: postgresql_privs
> postgresql_privs: fix can't revoke functions from user

- changelogs/fragments/693-idx-consider-schema.yaml
- plugins/modules/postgresql_idx.py
When checking to see if an index exists, the schema name needs to be taken into account.  That is, the same name can exist in multiple schemas.
Fixes #692
community.general.postgresql_idx
> postgresql_idx: consider schema name when checking

- changelogs/fragments/689-reconnect-before-upgrade.yml
- plugins/modules/postgresql_ext.py
The TimescaleDB extension needs a fresh connection at upgrade because the extension might be accidentally loaded. The [upgrade procedure](https://docs.timescale.com/self-hosted/latest/upgrades/minor-upgrade/) recommends using the `-X` flag of psql to ignore `.psqlrc` file that might execute some queries and load the extension.
This commit reconnects before performing the extension upgrade to fix the following error:
```
Traceback (most recent call last):
File "/tmp/ansible_community.postgresql.postgresql_ext_payload_yi1aki7a/ansible_community.postgresql.postgresql_ext_payload.zip/ansible_collections/community/postgresql/plugins/modules/postgresql_ext.py", line 428, in main
File "/tmp/ansible_community.postgresql.postgresql_ext_payload_yi1aki7a/ansible_community.postgresql.postgresql_ext_pa …
```
> fix(postgresql_ext): Reconnect before upgrade

- README.md
As per [this](https://matrix.to/#/!SizYskXSXykHzfalgv:matrix.org/$h4s_RN4zLDJ_scOm0oetJejBfuRdrXZK-kOB2uRMEF8?via=ansible.com&via=matrix.org&via=ansible.im) message, mark 2.x as EOL
> docs(readme): mark v2 as EOL

- .azure-pipelines/azure-pipelines.yml
- README.md
- shippable.yml
- tests/integration/targets/postgresql_info/tasks/main.yml
- tests/integration/targets/postgresql_slot/tasks/postgresql_slot_initial.yml
- tests/integration/targets/postgresql_subscription/tasks/main.yml
- tests/integration/targets/postgresql_user_obj_stat_info/tasks/postgresql_user_obj_stat_info.yml
- tests/integration/targets/setup_postgresql_db/tasks/main.yml
fixes #717 
Remove all references to CentOS 7 and RHEL 7, since both are EOL now. Additionally remove `when` conditions that are no longer needed w/ the death of CentOS 7.
> refactor(all): remove references to CentOS 7

- changelogs/fragments/722-user-configuration.yml
- plugins/module_utils/database.py
- plugins/modules/postgresql_user.py
- requirements.txt
- tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml
- tests/unit/plugins/module_utils/test_database.py
- tests/unit/plugins/modules/test_postgresql_user.py
PostgreSQL has the ability to set defaults for configuration parameters for roles. This means, that when that users logs in, the parameter for their session will be set to the default for their role instead of the global default.  
For example `work_mem` could be set to a different default for a specific role.  
The current state of the collection doesn't handle this in a good way, though it is possible to manage those using the `community.postgresql.postgresql_query` module. It would be better if those would be handled by the `community.postgresql.postgresql_user` module.  
This is what these changes do. Configuration defaults can be handled when the user is created and will be managed in an idempotent manner. To provide backwards-compatibility, omitting the new parameter on the module …
> Users configuration

- changelogs/fragments/725-privs-for-foreign-tables.yml
- plugins/modules/postgresql_privs.py
- tests/integration/targets/postgresql_privs/tasks/main.yml
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_foreign_tables.yml
Fixes #724 
`postgresql_privs`
See #724 for reproduction steps and the nature of the issue. The fix is straight-forward, we simply need to include `relkind='f'` in our acls check in order for foreign tables to be considered by the privs module
> Support grants and revokes on foreign tables

- changelogs/fragments/727-subscriptions-with-limited-columns.yml
- plugins/modules/postgresql_subscription.py
- tests/integration/targets/postgresql_subscription/defaults/main.yml
- tests/integration/targets/postgresql_subscription/tasks/main.yml
- tests/integration/targets/postgresql_subscription/tasks/postgresql_subscription_limited_role.yml
- tests/integration/targets/setup_postgresql_db/vars/Ubuntu-20-py3.yml
- tests/integration/targets/setup_postgresql_db/vars/Ubuntu-22-py3.yml
Fixes #726 
`postgresql_subscription`
Using https://github.com/ansible-collections/community.postgresql/pull/437 as a bit of an example of how to address this limitation. I've modified the module to first check to see which columns are available (per the information schema) and then adjusting the query accordingly. If the `subconninfo` column is not available, we deal with that by allowing the subscription to be created, but then logging a warning on subsequent runs if we are looking at a subscription that already exists. Without access to `subconninfo`, we have no way to compare the connection info provided to the module versus what exists in the database, so we simply skip.
I am having a hell of a time devising tests that will prove out that this fix works. I've …
> Handles subscriptions when subconninfo column is unavailable

- changelogs/fragments/731-db-fix-for-pg17.yml
- plugins/modules/postgresql_db.py
Fix `postgresql_db` for Postgres 17+ due to a column name change in pg_database.
Fixes: #729
`postgresql_db`
This appears to be the minimum required change for `postgresql_db` to work as expected with Postgres17 or higher whilst maintaining backwards compatibility.
> Fix postgresql_db for Postgres 17+

- changelogs/fragments/728_support_betas_and_rcs.yml
- plugins/modules/postgresql_info.py
- tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
Convert postgresql_info to using `current_setting('server_version_num')` as suggested by @keithf4 . This makes the version check work regardless if this is an actual release (`17.0`), a beta (`17beta3`), or an rc (`17rc1`) since the value for all is `170000`. 
Fixes #728 
```paste below
```
> fix(postgresql_info): use a server version check that handles beta and rc releases

- changelogs/fragments/1-pg_set.yml
- plugins/modules/postgresql_set.py
- tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/744
plugins/modules/postgresql_set.py
> postgresql_set: forbids to reset shared_preload_libraries with empty string

- changelogs/fragments/763-add-publication-with-specific-columns.yml
- plugins/modules/postgresql_publication.py
- tests/integration/targets/postgresql_publication/tasks/postgresql_publication_initial.yml
Fixes #609
Add possibility of creating publication with only specific columns
postgresql_publication
```paste below
postgresql_publication:
name: '{{ test_pub }}'
columns:
users:
- user_id
- email
some_other_table_with_al_columns: []
```
> Fixes #609 Publication with columns

- changelogs/fragments/0-postgresql_user.yml
- plugins/modules/postgresql_user.py
- tests/integration/targets/postgresql_user/tasks/test_password.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/688
IMPORTANT:
- The tests I added passed w/o any code change, so I failed to reproduce the bug
- But the tests check that the password is actually stored as MD5
- I carefully debugged and the tests poke the code I added, the code determines correctly that there's `scram-sha-256` on the server by default and executes pwchage = True
- If you think it's risky to add this code, say it, if we agree that it is, I'll close the PR
> pg_user doesn't take password_encryption into account when checking if a password should be updated

- changelogs/fragments/420-pg_hba-fix-hash-symbol-in-quotes.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
- tests/unit/plugins/modules/test_postgresql_pg_hba.py
- Fixes issue parsing `pg_hba.conf` files that contain a `#` in a quoted string
- When there is an issue parsing a `pg_hba.conf` file, we now print the number of the line where the issue is
- Adds tests for the modified and added functionality
Fixes #420 
postgresql_pg_hba
> Fix 420 comments parsing

- changelogs/fragments/772-refactoring-pg_hba-module.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
- tests/unit/plugins/modules/test_postgresql_pg_hba.py
This is a refactoring-only PR and another step on the refactoring and improvement-journey of that module.  
There is a minor change which is, that internally auth-options are now represented with dicts and not with strings anymore. This allows us to verify that the same key doesn't appear multiple times. The integration-tests have been changed to account for that.
There is one more change in the tests, which is due to ordering of rules. I don't know how or why this was the way it was. I'm going with how `ipaddress` sorts those networks, which I think makes sense:
```
In [6]: ipaddress.ip_network('::1/128') < ipaddress.ip_network('2001:db8::1/128')
Out[6]: True
```
Otherwise this doesn't change the modules behavior.
More changes: 
- adds unit-tests for the refactored rule-class
- adds …
> pg_hba module refactoring

- .azure-pipelines/azure-pipelines.yml
- README.md
AZP: replace Fedora40 -> Fedora41, RHEL9.4 -> RHEL9.5 in devel tests
Relates to https://github.com/ansible/ansible/pull/84281
> AZP: replace Fedora40 -> Fedora41, RHEL9.4 -> RHEL9.5 in devel tests

- changelogs/fragments/788-fix-postresql-info-db-connection.yml
- plugins/modules/postgresql_info.py
`postgresql_info` module fails if the user used for connection doesn't have permission to connect to last database from returned database list.
Fix:
After gathering the information about databases, connection is restored to the database specified in module parameters.
postgresql_info module
Issue with `postgresql_info` module:
When using AWS RDS, you never has access to `rdsadmin` database. If `rdsadmin` databases is return as a last one when listing databases, it keeps trying to connect th `rdsadmin` db when collecting other data, which fails, since you can't connect to the database.
How to reproduce:
Since the database list doesn't have fixed order, it is not that easy to reproduce.
> Reconnect to the default database after gathering databases info

- changelogs/fragments/0-postgresql_query.yml
- plugins/modules/postgresql_query.py
- tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/787
in case of one query it returns
```
"execution_time_ms": [
6.248
],
```
in case of 3 queries:
```
"execution_time_ms": [
0.2793,
0.1921,
0.1112
],
```
> postgresql_query: return a list containing execution time per query in milliseconds

- changelogs/fragments/0-postgresql_info.yml
- plugins/modules/postgresql_info.py
- tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
postgresql_info: fix when db used instead of login_db
fixes https://github.com/ansible-collections/community.postgresql/issues/794
> postgresql_info: fix when db used instead of login_db

- changelogs/fragments/0-postgresql_info.yml
- plugins/modules/postgresql_info.py
postgresql_info: deprecated db alias in favor of login_db
as multiple aliases can actually cause bugs like https://github.com/ansible-collections/community.postgresql/issues/794
i suggest deprecating and removing the `db` one in favor of `login_db`.
`db` is inconsistent with the other login arguments like `login_user`, `login_password`, etc. and it's even misleading. That's why the `login_db` alias was introduced.
I suggest deprecating it now and removing it in the next major release.
Created an [issue](https://github.com/ansible-collections/community.postgresql/issues/801) for milestone 4.0.0.
> postgresql_info: deprecated db alias in favor of login_db

- changelogs/fragments/0-postgresql-user.yml
- plugins/modules/postgresql_user.py
- Deprecates the `db` alias in favor of `login_db` as discussed in #801 
- `postgresql_user`
> deprecates the db-alias in postgresql_user

- changelogs/fragments/802-unquoted-config-values.yml
- plugins/modules/postgresql_user.py
- tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml
Adds a flag to turn off string-quoting for user-specific configuration, so settings like `search_path` can be set using the module.
Fixes #802 
This is not optimal, but the best solution I was able to come up with. See discussion in #802
> allow non-string settings in user-specific configuration

- .github/CODEOWNERS
- changelogs/fragments/778-pg-hba-improvements.yml
- plugins/modules/postgresql_pg_hba.py
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_bulk_rules.yml
- tests/integration/targets/postgresql_pg_hba/tasks/postgresql_pg_hba_initial.yml
- tests/unit/plugins/modules/test_postgresql_pg_hba.py
- Adding myself to the CODEOWNERS file for the parts related to `postgresql_pg_hba`
- Deprecates `keep_comments_at_rules` as discussed in #776 
- Adds parameter `sort_rules` that allows to disable sorting of rules. The default is `true` to keep to previous behavior
- Allows a file to contain `include` directives and will keep them at the end of the file. Does not allow to add such directives (#795)
- Adds the rendered string that is written to the file as an output
Fixes #776 
Fixes #795 
`postgresql_pg_hba`
- Removes the old `PgHba` class and moves the code to different stand-alone methods
- Adds tests for several edge-cases and new features
- modification in the tests is to account for the changes regarding `keep_comments_at_rules`
- adds required fetch in tests
> fixes and features for the pg_hba module

- changelogs/fragments/813-postgresql_publication-rowfilter.yml
- plugins/modules/postgresql_publication.py
- tests/integration/targets/postgresql_publication/tasks/postgresql_publication_initial.yml
Add **row filter** support to `postgresql_publication` module, via an extra yaml parameter named `rowfilters`
This feature is supported since PG Version 15 (search "WHERE" or "row filter"):
- https://www.postgresql.org/docs/15/sql-createpublication.html
- https://www.postgresql.org/docs/15/sql-alterpublication.html
Some design decisions:
1. the parameter allows the user to include or omit the `WHERE` clause. Internally, if the clause exists we remove it and then add it before constructing the SQL fragment. This simplifies, among other things, the row filter comparison described below. 
2. When it comes to idempotency, and detecting whether the row filter has changed or not, I opted for removing any quoting and whitespace and then compare the strings. The reason for that lies in how PG …
> postgresql_publication: add row filter support

- plugins/modules/postgresql_alter_system.py
- tests/integration/targets/postgresql_alter_system/tasks/main.yml
- tests/integration/targets/postgresql_alter_system/tasks/postgresql_alter_system_initial.yml
- tests/integration/targets/postgresql_alter_system/tasks/test_bools.yml
- tests/integration/targets/postgresql_alter_system/tasks/test_enums.yml
- tests/integration/targets/postgresql_alter_system/tasks/test_integers.yml
- tests/integration/targets/postgresql_alter_system/tasks/test_nonexistent.yml
- tests/integration/targets/postgresql_alter_system/tasks/test_reals.yml
- tests/integration/targets/postgresql_alter_system/tasks/test_resetting.yml
- tests/integration/targets/postgresql_alter_system/tasks/test_strings.yml
postgresql_alter_system: new module
**Why?**
- postgresql_set was developed by me when i was at the beginning of my contributor journey with all implications
- postgresql_set was developed when i was under pressure at my `$day_job` and family stuff at that time, so with no long term reliable design in mind, i.e. following the "waterfall" , "spagetti code" style
- postgresql_set, considering the above, is buggy and hard to fix w/o breaking. See as example https://github.com/ansible-collections/community.postgresql/issues/732 (i researched)
postgresql_alter_system:
- may be a replacement for postgresql_set, with proper deprecation and enough time for users to switch before removal
- all value type specific logic is isolated in corresponding classes
- the code is generally much better …
> postgresql_alter_system: new module

- changelogs/fragments/818-table-consider-schema-name.yaml
- plugins/modules/postgresql_table.py
The `postgresql_table` command shows spurious change status (and attempts unnecessary `ALTER TABLE...OWNER TO`) when multiple schemas have tables of the same name (which is the table being operated on by the task).
This happens because the query to get the existing information does not properly limit by schema name for the `pg_tables` view. It only limits for the `pg_namespace` part of the query. As a result, this query returns multiple rows, one per schema containing a table of the specified name.
Fixes #817
postgresql_table
BEFORE:
```
changed: [krls1.sip.wiktel.com] => (item=office) => changed=true
ansible_loop_var: item
invocation:
module_args:
ca_cert: null
cascade: false
columns:
- username                  varchar
- domain                    varchar
- …
```
> postgresql_table: Fix multiple schema handling (#817)

- changelogs/fragments/1-deprecate_rename.yml
- plugins/modules/postgresql_db.py
- plugins/modules/postgresql_sequence.py
- plugins/modules/postgresql_table.py
- plugins/modules/postgresql_tablespace.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/820
> Deprecate rename and rename_to choices/options

- changelogs/fragments/4-aliases.yml
- plugins/module_utils/postgres.py
- tests/unit/plugins/module_utils/test_postgres.py
Deprecate some login aliases
FYI there's also ``port`` (with ``login_port`` alias), but as it's not an alias I would tackle it in a separate PR later (no rush with it).
> Deprecate some login aliases

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-remove_lang.yml
- changelogs/fragments/1-remove_privs.yml
- changelogs/fragments/2-privs.yml
- changelogs/fragments/4-aliases.yml
- changelogs/fragments/5-python2.yml
- changelogs/fragments/6-set_deprecate.yml
> Release 4.0.0 commit

- changelogs/fragments/0-alter_system.yml
- plugins/modules/postgresql_alter_system.py
- tests/integration/targets/postgresql_alter_system/tasks/test_reals.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/853
> postgresql_alter_system: fix values returned in scientific notation

- changelogs/fragments/0-alter_system.yml
- plugins/modules/postgresql_alter_system.py
- tests/integration/targets/postgresql_alter_system/tasks/test_reals.yml
(cherry picked from commit f32de83d2c4fda21ef214a5e385edaa83cf64a1b)
backport of https://github.com/ansible-collections/community.postgresql/pull/854
As it's just a backport as-is (same changes that in main) and i didn't do any edits, merging w/o approval
> postgresql_alter_system: fix values returned in scientific notation (#854)

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-alter_system.yml
- galaxy.yml
> Release 3.14.1 commit

- .azure-pipelines/azure-pipelines.yml
- README.md
- tests/integration/targets/postgresql_privs/tasks/pg_authid_not_readable.yml
- tests/integration/targets/postgresql_privs/tasks/postgresql_privs_initial.yml
AZP: add RHEL 10.0 to devel remote target
Announced in https://forum.ansible.com/t/ansible-test-devel-rhel-10-0-added/42892
Let's give it a try
> AZP: add RHEL 10.0 to devel remote target

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/0-port.yml
- changelogs/fragments/858-negated-change-report.yml
- galaxy.yml
> Release 4.1.0 commit

- changelogs/fragments/865-postgresql_db-session_role-fix.yml
- plugins/modules/postgresql_db.py
- tests/integration/targets/postgresql_db/tasks/main.yml
- tests/integration/targets/postgresql_db/tasks/state_dump_restore_role.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/864
Fixes `postgresql_db` "session_role" behavior when state is `dump`/`restore` for binary (`.pgc`) archives.
It was being ignored but now it behaves as intended by pg_dump/pg_restore
postgresql_db
When pg_dump is used, the `--role` parameter is used to switch to a different user/role that has sufficient permissions to perform the dump.
When pg_restore is used, the `--role` parameter, in combination with `--no-owner`, allows you to restore the objects contained in the archive under new ownership (the one specified with `--role`).
Up to now, whenever pg_dump/pg_restore was used, the `session_role` parameter was being ignored and it would give surprising results (or errors).
Now the …
> postgresql_db: add session_role support for raw connections
