tests/unit/plugins/module_utils/test_postgres.py
Copy unit tests from community.general
=> Copy unit tests from community.general

plugins/modules/postgresql_copy.py, plugins/modules/postgresql_db.py, plugins/modules/postgresql_ext.py, plugins/modules/postgresql_idx.py, plugins/modules/postgresql_info.py, plugins/modules/postgresql_lang.py, plugins/modules/postgresql_membership.py, plugins/modules/postgresql_owner.py, plugins/modules/postgresql_ping.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_publication.py, plugins/modules/postgresql_query.py, plugins/modules/postgresql_schema.py, plugins/modules/postgresql_sequence.py, plugins/modules/postgresql_set.py, plugins/modules/postgresql_slot.py, plugins/modules/postgresql_subscription.py, plugins/modules/postgresql_table.py, plugins/modules/postgresql_tablespace.py, plugins/modules/postgresql_user.py, plugins/modules/postgresql_user_obj_stat_info.py
=> Fix imports

tests/unit/plugins/module_utils/test_saslprep.py
Copy saslprep unit tests from community.general
=> Copy saslprep unit tests from community.general

changelogs/config.yaml, changelogs/fragments/1048-postgresql_privs_add_procedure_type.yml, changelogs/fragments/1059-postgresql_privs_fix_failings_when_using_roles_with_hyphen.yml, changelogs/fragments/1078-postgresql_ext_fix_version_selection_when_version_is_latest.yml, changelogs/fragments/1091-postgresql_info_add_in_recovery_ret_val.yml, changelogs/fragments/1099-postgresql_ext_fix_failing_when_version_cannot_be_compared.yml, changelogs/fragments/886-postgresql_query_add_ret_vals.yml
Copy changelog fragments from community.geleral stable-1 branch
=> Copy changelog fragments from community.geleral stable-1 branch

plugins/modules/postgresql_copy.py, plugins/modules/postgresql_db.py, plugins/modules/postgresql_ext.py, plugins/modules/postgresql_idx.py, plugins/modules/postgresql_info.py, plugins/modules/postgresql_lang.py, plugins/modules/postgresql_membership.py, plugins/modules/postgresql_owner.py, plugins/modules/postgresql_ping.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_publication.py, plugins/modules/postgresql_query.py, plugins/modules/postgresql_schema.py, plugins/modules/postgresql_sequence.py, plugins/modules/postgresql_set.py, plugins/modules/postgresql_slot.py, plugins/modules/postgresql_table.py, plugins/modules/postgresql_tablespace.py, plugins/modules/postgresql_user.py, plugins/modules/postgresql_user_obj_stat_info.py
Copied from https://github.com/ansible-collections/community.general/pull/1170
Author @pzahemszky 
=> postgresql modules: Fix documentation of trust_input parameter

galaxy.yml
Update galaxy.yml to the next (expected) release version
=> Update galaxy.yml to the next (expected) release version

shippable.yml, tests/utils/shippable/units.sh
Based on https://github.com/ansible-collections/community.docker/pull/2
Run unit tests on one CI node
=> Run unit tests on one CI node

plugins/modules/postgresql_user.py
Fixes Fixes https://github.com/ansible-collections/community.general/issues/1217
`plugins/modules/postgresql_user.py`
=> postgresql_user: fix documentation formatting

plugins/modules/postgresql_copy.py, plugins/modules/postgresql_db.py, plugins/modules/postgresql_ext.py, plugins/modules/postgresql_idx.py, plugins/modules/postgresql_info.py, plugins/modules/postgresql_lang.py, plugins/modules/postgresql_membership.py, plugins/modules/postgresql_owner.py, plugins/modules/postgresql_pg_hba.py, plugins/modules/postgresql_ping.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_publication.py, plugins/modules/postgresql_query.py, plugins/modules/postgresql_schema.py, plugins/modules/postgresql_sequence.py, plugins/modules/postgresql_set.py, plugins/modules/postgresql_slot.py, plugins/modules/postgresql_subscription.py, plugins/modules/postgresql_table.py, plugins/modules/postgresql_tablespace.py, plugins/modules/postgresql_user_obj_stat_info.py
modules: fix documentation
modules
=> modules: fix documentation

changelogs/fragments/42-postgresql_set_add_message_when_parameter_not_found.yml, plugins/modules/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/41
`postgresql_set`
=> postgresql_set: Return a message when a passed parameter has not been found

changelogs/fragments/46-postgresql_query_fix_decimal_handling.yml, plugins/modules/postgresql_query.py, tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/45
=> postgresql_query: fix decimal handling

.azure-pipelines/azure-pipelines.yml, changelogs/fragments/52-postgresql_set_fix_b_values_handling.yml, plugins/modules/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/main.yml, tests/integration/targets/postgresql_set/tasks/options_coverage.yml, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/48
I also made additional tests tests/integration/targets/postgresql_set/tasks/options_coverage.yml
postgresql_set
=> postgresql_set: fix crashes caused by values containing 'b'

.azure-pipelines/azure-pipelines.yml
azure-pipelines: update container version
implements https://github.com/ansible-collections/overview/issues/45#issuecomment-776163864
=> azure-pipelines: update container version

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-20-py3.yml
azure-pipelines: add Ubuntu 20.04 to test matrix
https://github.com/ansible-collections/overview/issues/45#issuecomment-765670564
=> azure-pipelines: add Ubuntu 20.04 to test matrix

.azure-pipelines/azure-pipelines.yml
azure-pipelines: update devel test matrix
https://github.com/ansible-collections/overview/issues/45#issuecomment-776859063
Repository maintenance
=> azure-pipelines: update devel test matrix

plugins/modules/postgresql_ping.py, tests/integration/targets/setup_postgresql_db/tasks/main.yml
Enable CI for Centos 8
Repository maintenance
=> Enable CI for Centos 8

.azure-pipelines/azure-pipelines.yml, tests/unit/plugins/module_utils/test_postgres.py
Fix azure pipelines
- Repository Maintenance
=> Fix azure pipelines

tests/integration/targets/postgresql_set/tasks/options_coverage.yml
postgresql_set tests: fix comment
=> postgresql_set tests: fix comment

README.md
README: the collection documentation was migrated, fix broken links
=> README: the collection documentation was migrated, fix broken links

changelogs/fragments/70-postgresql_ping_add_ret_values.yml, plugins/modules/postgresql_ping.py, tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml
postgresql_ping: add patch, full, and raw fields to server_version return value
similar to https://github.com/ansible-collections/community.postgresql/pull/68
=> postgresql_ping: add patch, full, and raw fields to server_version return value

CONTRIBUTING.md
Add CONTRIBUTING.md with a Quick-start guide
Mostly copied https://github.com/ansible-collections/community.mysql/pull/112
=> Add CONTRIBUTING.md with a Quick-start guide

.azure-pipelines/azure-pipelines.yml
Update the default test container version
https://github.com/ansible-collections/overview/issues/45#issuecomment-807391460
=> Update the default test container version

CONTRIBUTING.md
Add refs to the committer guidelines
=> Add refs to the committer guidelines

CONTRIBUTING.md, REVIEW_CHECKLIST.md
=> Add REVIEW_CHECKLIST.md

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/68-postgresql_info_add_ret_values.yml, changelogs/fragments/70-postgresql_ping_add_ret_values.yml, galaxy.yml
=> Release 1.2.0 commit

galaxy.yml
Update galaxy.yml for the next expected version (this is according to the release [wiki](https://github.com/ansible/community/wiki/ReleasingCollections#releasing-without-release-branches-for-smaller-collections))
=> Update galaxy.yml for the next expected version

REVIEW_CHECKLIST.md
=> Fix REVIEW_CHECKLIST

.azure-pipelines/azure-pipelines.yml, tests/sanity/ignore-2.12.txt
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100
Tests: add support for 2.11
`.azure-pipelines/azure-pipelines.yml`
=> Tests: add support for 2.11

changelogs/fragments/87-postgresql_query_add_warn_announcement.yml, plugins/modules/postgresql_query.py
Relates to https://github.com/ansible-collections/community.postgresql/issues/85
=> postgresql_query: add announcement about changing the default value of the as_single_query option

.azure-pipelines/scripts/publish-codecov.sh, tests/utils/shippable/shippable.sh
https://github.com/ansible-collections/overview/issues/45#issuecomment-829350163
=> Updated codecov bash ref

.azure-pipelines/azure-pipelines.yml, shippable.yml
https://github.com/ansible-collections/overview/issues/45#issuecomment-830220740
=> Text matrix: add fedora34, remove fedora32 for devel

.azure-pipelines/azure-pipelines.yml, shippable.yml
Remove fedora34 from the test matrix
=> Update test matrix

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/82-fix-fail-on-role.yml, changelogs/fragments/87-postgresql_query_add_warn_announcement.yml
=> Release 1.3.0 commit

galaxy.yml
Update galaxy.yml to the next **expected** release version
=> Update galaxy.yml to the next expected release version

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/setup_postgresql_db/tasks/main.yml
=> Tests: enable Fedora34

README.md
README: add note how people can complain about abusive behavior
README.md
=> README: add note how people can complain about abusive behavior

MAINTAINERS, README.md
=> README.md: Add link to IRC

CONTRIBUTING.md, README.md
README.md, CONTRIBUTING.md: add links to the Maintainer guidelines
=> README.md, CONTRIBUTING.md: add links to the Maintainer guidelines

README.md
README: add a link to Libera.Chat
=> README: add a link to Libera.Chat

plugins/doc_fragments/postgres.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/111
Comment https://github.com/ansible-collections/community.postgresql/issues/111#issuecomment-876442205
`plugins/doc_fragments/postgres.py`
=> Update the login_host option documentation.

MAINTAINING.md, README.md
Add MAINTAINING.md, update README.md
=> Add MAINTAINING.md, update README.md

plugins/modules/postgresql_user.py, tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/122
postgresql_user: clarify docs, add debug_info ret var, add integration tests
(i don't thing a changelog fragment is needed here)
=> postgresql_user: clarify docs, add debug_info ret var, add integration tests

plugins/modules/postgresql_pg_hba.py
Relates https://github.com/ansible-collections/overview/issues/45#issuecomment-897333102
=> postgresql_pg_hba: fix sanity issues

plugins/modules/postgresql_query.py
postgresql_query: Code refactoring for better readability.
The code related to `convert_elements_to_pg_arrays(positional_args)` worked because it also changed module.params['positional_args'] by reference.
plugins/modules/postgresql_query.py
=> postgresql_query: Code refactoring for better readability.

plugins/module_utils/postgres.py
module_utils.postgres.get_conn_params: improve readability
=> module_utils.postgres.get_conn_params: improve readability

changelogs/fragments/145-postgresql_set_fix_wrong_value_conversion.yml, plugins/modules/postgresql_set.py, tests/unit/plugins/modules/test_postgresql_set.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/110
postgresql_set: fix wrong value conversion
=> postgresql_set: fix wrong value conversion

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/120-postgresql_correct_server_version_check.yml, changelogs/fragments/134-postgresql_pg_hba-rule-specific-comments.yml, changelogs/fragments/138-postgresql_info_fix_ver_handling.yml, changelogs/fragments/145-postgresql_set_fix_wrong_value_conversion.yml, changelogs/fragments/drop_db_with_force.yml
=> Release 1.5.0 commit

galaxy.yml
galaxy.yml: Increase version number to the next expected
=> galaxy.yml: Increase version number to the next expected

CONTRIBUTORS
CONTRIBUTORS: add more contributors
=> CONTRIBUTORS: add more contributors

plugins/modules/postgresql_privs.py, tests/utils/shippable/shippable.sh
=> CI: Fix sanity error

plugins/modules/postgresql_user.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.9.txt
Fixes https://github.com/ansible-collections/community.postgresql/issues/161
=> postgresql_user: Get rid of wrong documentation

.azure-pipelines/azure-pipelines.yml
=> CI: update AZP matrix

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/163-better_handling_of_postgresql_extensions.yml
=> Release 1.6.0 commit

changelogs/fragments/171-postgres_info__was_not_working_on_aws_rds_postgres.yml, plugins/modules/postgresql_info.py
closes #170
closes #169 
@MichaelDBA please code review if you may. Thank you for your help!
=> pg_authid is not avaialble on aws rds postgres

plugins/modules/postgresql_ping.py
Relates to https://github.com/ansible-collections/community.postgresql/issues/174
=> postgresql_ping: improve documentation

changelogs/fragments/178-prepare_for_distutils_be_removed.yml, plugins/module_utils/_version.py, plugins/module_utils/version.py
https://github.com/ansible-collections/community.postgresql/pull/178
=> Use vendored version of distutils.version instead of the deprecated Python standard library distutils

changelogs/fragments/185-postgresql_query_as_single_query_true.yml, plugins/modules/postgresql_query.py, tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
This breaking change was announced in https://github.com/ansible-collections/community.postgresql/pull/86
Relates to
- https://github.com/ansible-collections/community.postgresql/issues/85
- https://github.com/ansible-collections/community.postgresql/issues/180
=> postgresql_query: set as_single_query default as True

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/177-postgresql_ping_add_conn_err_msg_ret_val.yml, galaxy.yml
=> Release 1.7.0 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/177-postgresql_ping_add_conn_err_msg_ret_val.yml, changelogs/fragments/185-postgresql_query_as_single_query_true.yml, galaxy.yml
=> Release 2.0.0 commit

changelogs/fragments/0_deprecation_announcement.yml, plugins/modules/postgresql_query.py
Relates to https://github.com/ansible-collections/community.postgresql/issues/189
=> postgresql_query: deprecate script related options and return values

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0_deprecation_announcement.yml, galaxy.yml
=> Release 2.1.0 commit

MAINTAINERS
MAINTAINERS: add new maintainer
=> MAINTAINERS: add new maintainer

MAINTAINERS, changelogs/fragments/0-postgresql_query_fix.yml, plugins/modules/postgresql_query.py, tests/integration/targets/postgresql_query/files/test0.sql, tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Backport recent PRs to stable-1
- https://github.com/ansible-collections/community.postgresql/pull/193
- https://github.com/ansible-collections/community.postgresql/pull/192
=> [stable-1] Backport recent PRs to stable-1

changelogs/fragments/1-postgresq_connection_fix.yml, plugins/module_utils/postgres.py, tests/unit/plugins/module_utils/test_postgres.py
[stable-1] Backport changes made with https://github.com/ansible-collections/community.postgresql/pull/196
=> [stable-1] Backport changes

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_query_fix.yml, changelogs/fragments/1-postgresq_connection_fix.yml, galaxy.yml
=> Release 1.7.1 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_query_fix.yml, changelogs/fragments/1-postgresq_connection_fix.yml, galaxy.yml
=> Release 2.1.1 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0_deprecation_announcement.yml, galaxy.yml
=> Release 2.1.2 commit

plugins/modules/postgresql_query.py
postgresql_query: remove unused import
=> postgresql_query: remove unused import

tests/sanity/ignore-2.14.txt
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/13
=> Copy ignore-2.13.txt to ignore-2.14.txt

plugins/module_utils/postgres.py, plugins/modules/postgresql_user.py
postgresql_user: refactoring
(it relates to preparations for psycopg3 support introduction)
=> postgresql_user: refactoring

README.md
README: update list of ansible-core versions we test against
=> README: update list of ansible-core versions we test against

tests/utils/shippable/shippable.sh
Fixes https://github.com/ansible-collections/community.postgresql/issues/232
Last time appeared in https://github.com/ansible-collections/community.postgresql/pull/227
=> CI: replace community.general galaxy intallation with git installation

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_db_deprecated_alias.yml, changelogs/fragments/0-postgresql_user_depraction_of_privs.yml, galaxy.yml
=> Release 1.7.2 commit (#186)

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_db_deprecated_alias.yml, changelogs/fragments/0-postgresql_user_depraction_of_privs.yml, galaxy.yml
=> Release 2.1.3 commit

.azure-pipelines/azure-pipelines.yml
AZP: fix a typo (needs to be backported after merging)
=> AZP: fix a typo

docs/docsite/links.yml
=> add new docsite links feature

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/remove-2.9-2.10-compatability.yml, galaxy.yml
=> Release 1.7.3 commit (#186)

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/remove-2.9-2.10-compatability.yml, galaxy.yml
=> Release 2.1.4 commit

README.md, docs/docsite/links.yml
Update the README and docsite links to point to the new PG-specific Matrix room
=> docs: announce the new matrix pg room

tests/unit/plugins/module_utils/test_postgres.py
Update unit tests
Relates to https://github.com/ansible-collections/community.postgresql/pull/253
=> Update unit tests

changelogs/fragments/issue_240_doc_change.yml, plugins/modules/postgresql_owner.py
Backport of https://github.com/ansible-collections/community.postgresql/pull/256
=> [stable-1] postgresql_owner: doc improvement

.github/CODEOWNERS, CONTRIBUTORS, MAINTAINERS
This PR
- adds a new maintainer
- adds new contributors (PRs, Issue authors and folks who actively took part in the discussions there)
=> Add new maintainer and contributors

PSF-license.txt, changelogs/fragments/psf-license.yml, plugins/module_utils/_version.py
doc: add changelog fragment
fix: correct license path in _version.py
=> fix: add missing license file

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/psf-license.yml, galaxy.yml
=> Release 1.7.4 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/252-fix-none-attribute-error.yml, changelogs/fragments/psf-license.yml, galaxy.yml
=> Release 2.1.5 commit

changelogs/fragments/all_in_schema.yml, plugins/modules/postgresql_privs.py
=> backport 282

.azure-pipelines/azure-pipelines.yml
For the 'devel' branch, adjust the pipeline:
- remove fedora 34
- remove rhel 8.5
- add fedora 35
- add fedora 36
- add rhel 8.6
All as per https://github.com/ansible-collections/news-for-maintainers/issues/17
=> test: adjust the azure pipeline

.azure-pipelines/azure-pipelines.yml
=> Fix CI matrix

.azure-pipelines/azure-pipelines.yml
Drop Python 3.8 from the Azure pipeline
As per: [#18](https://github.com/ansible-collections/news-for-maintainers/issues/18)
pipeline
=> fix: update pipeline as per https://github.com/ansible-collections/news-for-maintainers/issues/18

changelogs/fragments/301-postgresql_user_idempotent_scram.yml
Add a fragment for https://github.com/ansible-collections/community.postgresql/pull/302
=> Add a changelog fragment for PR 302

changelogs/fragments/0-postgresql_set_avoid_quoting.yml, plugins/modules/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/options_coverage.yml, tests/integration/targets/setup_postgresql_db/vars/Debian-8.yml, tests/integration/targets/setup_postgresql_db/vars/RedHat-py3.yml, tests/integration/targets/setup_postgresql_db/vars/RedHat.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-12.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-14.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-16-py3.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-16.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-18-py3.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-20-py3.yml, tests/integration/targets/setup_postgresql_db/vars/default-py3.yml, tests/integration/targets/setup_postgresql_db/vars/default.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/78
postgresql_set
=> postgresql_set: get rid of extra quoting when passing list values

.azure-pipelines/azure-pipelines.yml, tests/integration/targets/postgresql_info/defaults/main.yml, tests/integration/targets/postgresql_info/tasks/setup_publication.yml, tests/integration/targets/postgresql_subscription/defaults/main.yml, tests/integration/targets/postgresql_subscription/tasks/setup_publication.yml, tests/integration/targets/setup_postgresql_replication/defaults/main.yml, tests/integration/targets/setup_postgresql_replication/tasks/setup_postgresql_cluster.yml
remove Ansible 2.11 from Azure pipeline
=> ci(azure pipeline): remove Ansible 2.11 from Azure pipeline

tests/integration/targets/postgresql_info/defaults/main.yml, tests/integration/targets/postgresql_info/tasks/setup_publication.yml, tests/integration/targets/postgresql_subscription/defaults/main.yml, tests/integration/targets/postgresql_subscription/tasks/setup_publication.yml, tests/integration/targets/setup_postgresql_replication/tasks/setup_postgresql_cluster.yml
=> postgresql_replication CI: clean up

plugins/doc_fragments/postgres.py, plugins/modules/postgresql_db.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_schema.py, plugins/modules/postgresql_sequence.py, plugins/modules/postgresql_table.py, plugins/modules/postgresql_user.py
Fix sanity errors
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/25
=> Fix sanity errors

plugins/doc_fragments/postgres.py, plugins/modules/postgresql_db.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_schema.py, plugins/modules/postgresql_sequence.py, plugins/modules/postgresql_table.py, plugins/modules/postgresql_user.py
Backport of https://github.com/ansible-collections/community.postgresql/pull/367
=> [stable-1] Fix sanity errors

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_set_avoid_quoting.yml, changelogs/fragments/301-postgresql_user_idempotent_scram.yml, changelogs/fragments/314-postgresql_info-quote-show-args.yml, changelogs/fragments/351-postgresql_pg_hba-add-connection-types.yml, galaxy.yml
=> Release 1.7.6 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_set_avoid_quoting.yml, changelogs/fragments/301-postgresql_user_idempotent_scram.yml, changelogs/fragments/314-postgresql_info-quote-show-args.yml, changelogs/fragments/329-postgresql_add_connect_params_field.yml, changelogs/fragments/332-postgresql_privs_def_privs_schemas.yml, changelogs/fragments/351-postgresql_pg_hba-add-connection-types.yml, galaxy.yml
=> Release 2.3.0 commit

CONTRIBUTORS, README.md
REAME.md, CONTRIBUTORS: update
@jegj @benformosa @rgl @Boosai @gotmax23 @jmighion @SantiRaposo @Vanav @Jhiliano @btoussaint @amossc @codrinh thank you for contributing to this project!
=> REAME.md, CONTRIBUTORS: update

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_privs.yml, galaxy.yml
=> Release 2.3.1 commit

changelogs/fragments/383-postgresql_privs_fix_schemas_with_special_names.yml, plugins/modules/postgresql_privs.py, tests/integration/targets/postgresql_privs/defaults/main.yml, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
backport to version 1 of PR #382
=> [stable-1] backport: postgresql_privs: fix schema quoting

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/383-postgresql_privs_fix_schemas_with_special_names.yml, galaxy.yml
=> Release 1.7.7 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/378-postgresql_pg_hba_fix_change_detection.yml, changelogs/fragments/379-postgresql_privs.yml, changelogs/fragments/382-postgresql_privs_fix_schemas_with_special_names.yml, galaxy.yml
=> Release 2.3.2 commit

.azure-pipelines/azure-pipelines.yml
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/31
=> AZP: Update CI matrix

changelogs/fragments/0-postgresql_query.yml, plugins/modules/postgresql_query.py, tests/integration/targets/postgresql_query/tasks/postgresql_query_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/312
If we merge it, issues in https://github.com/ansible-collections/community.postgresql/milestones/3.0.0 should be updated
=> postgresql_query: a list of queries can be passed

README.md
Update the README to indicate that the collection discussion is on Matrix
N/A
N/A
=> docs: update README to indicate the discussion room is on Matrix

README.md
=> README: improve badge

plugins/modules/postgresql_pg_hba.py
Fix sanity test in [postgresql_pg_hba.py](https://github.com/ansible-collections/community.postgresql/blob/main/plugins/modules/postgresql_pg_hba.py)
=> Fix sanity test

plugins/modules/postgresql_script.py, plugins/modules/postgresql_tablespace.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.9.txt
Fix sanity as new sanity checks have been recently introduced and [announced](https://github.com/ansible-collections/news-for-maintainers/issues) by core team
=> Fix sanity

plugins/modules/postgresql_pg_hba.py
backport of https://github.com/ansible-collections/community.postgresql/pull/409
=> [stable-1] Fix sanity test

plugins/modules/postgresql_tablespace.py, tests/sanity/ignore-2.10.txt, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.9.txt
(cherry picked from commit 7c9e27b0d4c7003e691f03ea7d022d2337a1ce77)
Backport of https://github.com/ansible-collections/community.postgresql/pull/414
=> [stable-1] Fix sanity (#414)

plugins/modules/postgresql_user.py
added info about using SCRAM-SHA-256 (& not only md5) hashed passwords.
=> postgresql_user.py - Documentation

changelogs/fragments/0-postgresql_info.yml, plugins/modules/postgresql_info.py, plugins/modules/postgresql_sequence.py
Fixed changelog and fixed documentation
Changelog correction on the issue #429
Correction of documentation on the issue #338 
=> Fixed changelog and fixed documentation

tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml, tests/integration/targets/setup_postgresql_replication/defaults/main.yml, tests/integration/targets/setup_postgresql_replication/handlers/main.yml, tests/integration/targets/setup_postgresql_replication/tasks/setup_postgresql_cluster.yml
=> Fix CI tests, postgresql_info and _subscription integration tests now use PostgreSQL 15 (#445)

.azure-pipelines/azure-pipelines.yml, tests/sanity/ignore-2.16.txt
Relates to https://github.com/ansible-collections/news-for-maintainers/issues/41
Solution of the issue #443
=> Add testing against ansible-core 2.15

tests/integration/targets/postgresql_db/tasks/state_dump_restore.yml, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml, tests/integration/targets/postgresql_set/tasks/options_coverage.yml, tests/integration/targets/setup_postgresql_db/tasks/main.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-12.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-14.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-16-py3.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-16.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-18-py3.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-20-py3.yml
Changed the PostgreSQL version in integration tests from 14 to 15 for Ubuntu 20.04 
fixes #446 
=> Changed the PostgreSQL version in integration tests from 14 to 15 for Ubuntu 20.04

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_info.yml, changelogs/fragments/0-postgresql_set_avoid_handle_ip_addresses.yml, changelogs/fragments/0-postgresql_set_avoid_wrong_values.yml, changelogs/fragments/0-postgresql_user.yml, changelogs/fragments/399-missing-import.yml, changelogs/fragments/428-postgres_info_support_non_numeric_extenstion_version.yml, changelogs/fragments/451-postgresql_privs_fix_connect_params_being_ignored.yml, galaxy.yml
Release 1.7.8 from branch stable-1
=> Release 1.7.8

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_privs.yml, galaxy.yml
=> Release 1.7.9 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_privs.yml, galaxy.yml
=> Release 2.4.1 commit

MAINTAINERS
MAINTAINERS: add a new maintainer, sort the list alphabetically
Please add the `backport-1` label after merge
=> MAINTAINERS: add a new maintainer, sort the list alphabetically

changelogs/fragments/0-postgresql_info.yml, plugins/modules/postgresql_db.py, plugins/modules/postgresql_info.py, plugins/modules/postgresql_ping.py, plugins/modules/postgresql_privs.py
Fixes #465
Added database connection closure for modules:
- postgresql_ping
- postgresql_info
- postgresql_privs
=> Added closing the database connection after completing the task

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_info.yml, galaxy.yml
=> Release 1.7.10 commit

changelogs/fragments/1-postgresql_privs.yml, plugins/modules/postgresql_privs.py, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/208
=> postgresql_privs: remove deprecated usage_on_types argument

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_query.yml, changelogs/fragments/1-postgresql_privs.yml, changelogs/fragments/3-postgresql_user.yml, changelogs/fragments/4-postgresql_user.yml, changelogs/fragments/5-postgresql_pg_hba.yml, galaxy.yml
=> Release 3.0.0 commit

changelogs/fragments/510-postgresql_privs.yml, plugins/modules/postgresql_privs.py
My PR fixes and error message in postgresql_privs module and fixed an error in docs introduced in PR #500 .
=> postgresql_privs - Fixed error message and documentation

tests/integration/targets/postgresql_ping/defaults/main.yml, tests/integration/targets/postgresql_ping/handlers/main.yml, tests/integration/targets/postgresql_ping/tasks/main.yml, tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml
postgresql_ping integration tests: brush up
i wrote them many years ago, it's time to brush it up a bit
=> postgresql_ping integration tests: brush up

tests/integration/targets/postgresql_ping/defaults/main.yml, tests/integration/targets/postgresql_ping/tasks/main.yml, tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml
Backport of https://github.com/ansible-collections/community.postgresql/pull/524
=> [stable-1] postgresql_ping integration tests: brush up

plugins/module_utils/postgres.py, plugins/modules/postgresql_ext.py, plugins/modules/postgresql_idx.py, plugins/modules/postgresql_info.py, plugins/modules/postgresql_lang.py, plugins/modules/postgresql_ping.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_slot.py, plugins/modules/postgresql_table.py, plugins/modules/postgresql_tablespace.py, plugins/modules/postgresql_user.py, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
Modifying all psycopg results to use dictionary keys, and casting all ACL type data as varchar. 
This will ensure the same code will work with Psycopg 3, helping with #499. 
Many modules
These changes were tested with Psycopg 3 in #517.
=> Psycopg dictionary results

tests/integration/targets/postgresql_ping/tasks/postgresql_ping_initial.yml
postgresql_ping integration tests: change assertions titles
=> postgresql_ping integration tests: change assertions titles

tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/utils/shippable/check_matrix.py
Replaced urlopen with open_url
Tests utilities
=> Using open_url

plugins/modules/postgresql_privs.py
Moved the psycopg library check from the module to postgres.py, to use the same pattern as all other modules.
And removed some unused code.
- Refactoring Pull Request
This PR will simplify the addition of psycopg3 support and help with #499
=> Psycopg refactor in privs

plugins/module_utils/postgres.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_query.py, plugins/modules/postgresql_script.py, plugins/modules/postgresql_user.py, tests/unit/plugins/module_utils/test_postgres.py
Refactor the code to simplify the addition of Psycopg 3 support.
Module refactoring
module_utils/postgres 
postgresql_script
This could be the last refactoring PR before we add Psycopg 3 support for #499.
=> Psycopg refactoring

CONTRIBUTORS, plugins/modules/postgresql_ext.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_set.py, plugins/modules/postgresql_tablespace.py
Updated authors list in ext, privs, set, and tablespace modules (missed that in my past PRs).
postgresql_ext 
postgresql_set
postgresql_tablespace
=> Updated authors list in ext, privs, set, and tablespace modules

tests/unit/plugins/module_utils/test_postgres.py
Partial backport of https://github.com/ansible-collections/community.postgresql/pull/557
=> [stable-2] Fix yamllint sanity errors

tests/unit/plugins/module_utils/test_postgres.py
Partial backport of https://github.com/ansible-collections/community.postgresql/pull/557
=> [stable-1] Fix yamllint sanity errors

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/481-postgresql_privs.yml, changelogs/fragments/502_postgresql_privs.yml, changelogs/fragments/504_postgresql_ext.yml, changelogs/fragments/505-postgresql_set.yml, changelogs/fragments/510-postgresql_privs.yml, changelogs/fragments/518-psycopg-server_version.yml, changelogs/fragments/521-postgresql_set.yml, changelogs/fragments/522-psycopg-cursor_args.yml, changelogs/fragments/545_postgresql_ext.yml, changelogs/fragments/554_postgresql_tablespace.yml, changelogs/fragments/556_psycopg251.yml, changelogs/fragments/559-postgresql_lang-deprecate.yml, galaxy.yml
=> Release v3.1.0 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/505-postgresql_set.yml, changelogs/fragments/559-postgresql_lang-deprecate.yml, galaxy.yml
=> Release v1.7.11 commit

README.md, changelogs/fragments/517_psycopg3.yml, plugins/doc_fragments/postgres.py, plugins/module_utils/database.py, plugins/module_utils/postgres.py, plugins/modules/postgresql_copy.py, plugins/modules/postgresql_db.py, plugins/modules/postgresql_privs.py, plugins/modules/postgresql_query.py, plugins/modules/postgresql_script.py, plugins/modules/postgresql_user.py, tests/integration/targets/setup_postgresql_db/vars/Fedora-36-py3.yml, tests/integration/targets/setup_postgresql_db/vars/Ubuntu-22-py3.yml, tests/unit/plugins/module_utils/test_postgres.py
Added support for Psycopg 3
Fixes #499
All modules
Work in progress, any feedback welcome
=> Psycopg 3 support

changelogs/fragments/570_postgresql_info.yml, plugins/modules/postgresql_info.py
Fix SQL syntax error in postgresql_info
Fixes #570 
```paste below
```
=> Fix SQL syntax error in postgresql_info

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/517_psycopg3.yml, changelogs/fragments/555_postgresql_owner.yml, changelogs/fragments/570_postgresql_info.yml, changelogs/fragments/nuke_contributors.yml, galaxy.yml
=> Release 3.2.0

README.md
Relates to https://github.com/ansible-collections/community.postgresql/discussions/544
=> README: Add mission statement

.azure-pipelines/azure-pipelines.yml, .flake8, CONTRIBUTING.md, plugins/module_utils/version.py, plugins/modules/postgresql_pg_hba.py, tests/unit/plugins/module_utils/test_saslprep.py, tox.ini
simply trying to use some standard python tool to make the code easier to read.
=> Add some basic python code quality practice

changelogs/fragments/585-decode-data-from-sql_ascii-databases.yml, plugins/modules/postgresql_user.py, tests/integration/targets/postgresql_user/defaults/main.yml, tests/integration/targets/postgresql_user/tasks/main.yml, tests/integration/targets/postgresql_user/tasks/postgresql_user_sql_ascii_db.yml, tests/integration/targets/setup_postgresql_db/defaults/main.yml, tests/integration/targets/setup_postgresql_db/tasks/main.yml, tests/integration/targets/setup_postgresql_db/tasks/sql_ascii.yml
- New Module Pull Request
```paste below
```
=> [stable-1] Decode bytes object from sql_ascii databases (#585)

changelogs/fragments/585-decode-data-from-sql_ascii-databases.yml, plugins/modules/postgresql_user.py, tests/integration/targets/postgresql_user/defaults/main.yml, tests/integration/targets/postgresql_user/tasks/main.yml, tests/integration/targets/postgresql_user/tasks/postgresql_user_sql_ascii_db.yml, tests/integration/targets/setup_postgresql_db/defaults/main.yml, tests/integration/targets/setup_postgresql_db/tasks/main.yml, tests/integration/targets/setup_postgresql_db/tasks/sql_ascii.yml
(cherry picked from commit 875dc95c70db816ccc3c0e45bd7294db31839db3)
- New Module Pull Request
```paste below
```
=> [stable-2] Decode bytes object from sql_ascii databases (#585)

.azure-pipelines/azure-pipelines.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/595
Closes https://github.com/ansible-collections/community.postgresql/pull/600
- Removes testing against core 2.12 (EOL)
- Removes not supported distros
- Updates distros
=> AZP: update matrix

.codespell-exclude-file, .codespell-exclude-words, .codespellrc, README.md
simply reply to https://github.com/ansible-collections/community.postgresql/issues/591 to use the new Galaxy NG url
=> Adapt galaxy URL for Galaxy NG

.azure-pipelines/azure-pipelines.yml
Backport of https://github.com/ansible-collections/community.postgresql/pull/605
=> [stable-2] AZP: update matrix

README.md
README: Discussions on the forum instead of GitHub Discussions feature
=> README: Discussions on the forum instead of GitHub Discussions feature

README.md
README: Update release support timeline
Implements https://github.com/ansible-collections/community.postgresql/discussions/526
=> README: Update release support timeline

README.md
Manual backport of https://github.com/ansible-collections/community.postgresql/pull/613
=> [stable-1] README: Update release support timeline

README.md
manual backport of https://github.com/ansible-collections/community.postgresql/pull/613
=> [stable-2] README: Update release support timeline

.azure-pipelines/azure-pipelines.yml
Implement [#62](https://github.com/ansible-collections/news-for-maintainers/issues/62)
- CI/CD
=> ci(azure pipeline): bump rhel from 9.2 to 9.3 for remote tests

tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
Fix integration jinja complaints
=> Fix integration jinja complaints

plugins/module_utils/postgres.py, plugins/modules/postgresql_db.py, plugins/modules/postgresql_user.py, tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml
postgresql_user, postgresql_db: use shared functions
=> postgresql_user, postgresql_db: use shared functions

changelogs/fragments/1-postgresql_schema.yml, plugins/module_utils/postgres.py, plugins/modules/postgresql_schema.py, plugins/modules/postgresql_user.py, tests/integration/targets/postgresql_schema/tasks/postgresql_schema_initial.yml
partly solves https://github.com/ansible-collections/community.postgresql/issues/354
=> Pg schema add comment argument

changelogs/fragments/3-postgresql_tablespace.yml, plugins/modules/postgresql_tablespace.py, tests/integration/targets/postgresql_tablespace/tasks/postgresql_tablespace_initial.yml
partly solves https://github.com/ansible-collections/community.postgresql/issues/354
=> postgresql_tablespace: add comment argument

changelogs/fragments/6-postgresql_subscription.yml, plugins/modules/postgresql_subscription.py, tests/integration/targets/postgresql_subscription/tasks/postgresql_subscription_initial.yml
=> postgresql_subscription: add comment argument

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_db.yml, changelogs/fragments/1-postgresql_schema.yml, changelogs/fragments/3-postgresql_tablespace.yml, changelogs/fragments/4-postgresql_ext.yml, changelogs/fragments/5-postgresql_publication.yml, changelogs/fragments/585-decode-data-from-sql_ascii-databases.yml, changelogs/fragments/592-return-not-changed-for-show.yml, changelogs/fragments/6-postgresql_subscription.yml, galaxy.yml
=> Release 3.3.0 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/585-decode-data-from-sql_ascii-databases.yml, changelogs/fragments/592-return-not-changed-for-show.yml, galaxy.yml
=> Release 2.4.4 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/585-decode-data-from-sql_ascii-databases.yml, galaxy.yml
=> Release 1.7.12 commit

plugins/modules/postgresql_tablespace.py, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.17.txt
postgresql_tablespace: Fix sanity check requirements violation
relates to https://github.com/ansible-community/package-test-results/issues/1
=> postgresql_tablespace: Fix sanity check requirements violation

changelogs/fragments/0-privs.yml, plugins/modules/postgresql_privs.py, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/668
I reproduced the bug, here's a fix
=> postgresql_privs: fix a failure when grant_option true

CHANGELOG.rst, changelogs/fragments/667-db_icu_provider.yml, plugins/modules/postgresql_db.py, plugins/modules/postgresql_info.py, tests/integration/targets/postgresql_db/defaults/main.yml, tests/integration/targets/postgresql_db/tasks/postgresql_db_initial.yml
Add support for **icu_locale** and **locale_provider** to **postgresql_db module**
- Feature Pull Request - [issue 666](https://github.com/ansible-collections/community.postgresql/issues/666)
**postgresql_db**
Hopefully, the pull request will be usable to show the missing feature.
closes #666
=> Add support for icu_locale and locale_provider postgresql_db module.

changelogs/fragments/0-privs.yml, plugins/modules/postgresql_privs.py, tests/integration/targets/postgresql_privs/tasks/postgresql_privs_general.yml
(cherry picked from commit 41c3f30c3180519d4526c838f3d70a44cdf6ca67)
Backport of https://github.com/ansible-collections/community.postgresql/pull/669
=> [stable-2] postgresql_privs: fix a failure when grant_option true (#669)

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-privs.yml, galaxy.yml
=> Release 2.4.5 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-privs.yml, changelogs/fragments/667-db_icu_provider.yml, galaxy.yml
=> Release 3.4.0 commit

CONTRIBUTING.md
=> CONTRIBUTING.md: improve

CONTRIBUTING.md
Co-authored-by: Douglas J Hunley <doug.hunley@gmail.com>
(cherry picked from commit caabfe66f2efb9ee5f9983b5bdb519aab11e3fdc)
Backport of https://github.com/ansible-collections/community.postgresql/pull/674
=> [stable-2] CONTRIBUTING.md: improve (#674)

README.md
README: put the collection version 1.* is EOL
Fixes https://github.com/ansible-collections/community.postgresql/issues/673
=> README: put the collection version 1.* is EOL

README.md
Co-authored-by: Douglas J Hunley <doug.hunley@gmail.com>
(cherry picked from commit 5b157024978a35bc3a4f51ddf9fc1fff910f7fef)
backport of https://github.com/ansible-collections/community.postgresql/pull/679
=> [stable-2] README: update communication guide (#679)

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/681-restore-custom-format-as-file.yml, changelogs/fragments/690-revoke-functions-from-user.yaml, changelogs/fragments/693-idx-consider-schema.yaml, changelogs/fragments/695-reconnect-before-upgrade.yml, galaxy.yml
=> Release 2.4.6 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/681-restore-custom-format-as-file.yml, changelogs/fragments/689-reconnect-before-upgrade.yml, changelogs/fragments/690-revoke-functions-from-user.yaml, changelogs/fragments/693-idx-consider-schema.yaml, galaxy.yml
=> Release 3.4.1 commit

.azure-pipelines/azure-pipelines.yml
Update the Quay container version in the Azure pipeline. Fixes #702
=> ci(azure): update the Quay container image version; fixes #702

changelogs/fragments/0-postgresql_publication.yml, plugins/modules/postgresql_publication.py, tests/integration/targets/postgresql_publication/tasks/postgresql_publication_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/709
=> postgresql_publication: add ability to specify schemas to add to publication

README.md
Reshuffle README wrt importance of communication and shift to the forum as Ansible official communication platform.
https://forum.ansible.com/t/proposal-consolidating-ansible-discussion-platforms/6812
=> README: reorg wrt communication

README.md
README: update communication section
=> README: update communication section

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_publication.yml, changelogs/fragments/714-infinity.yaml, changelogs/fragments/715-datestyle.yaml, changelogs/fragments/722-user-configuration.yml, galaxy.yml
=> Release 3.5.0 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/725-privs-for-foreign-tables.yml, changelogs/fragments/727-subscriptions-with-limited-columns.yml, changelogs/fragments/728_support_betas_and_rcs.yml, changelogs/fragments/731-db-fix-for-pg17.yml, galaxy.yml, tests/unit/plugins/modules/test_postgresql_user.py
=> Release 3.6.0 commit

README.md, tests/unit/plugins/modules/test_postgresql_user.py
README: Add info about PG versions support
As was discussed on Matrix
=> README: Add info about PG versions support

docs/docsite/links.yml
docs/docsite/links.yml: remove ML and IRC, add Forum team
=> docs/docsite/links.yml: remove ML and IRC, add Forum team

CHANGELOG.rst, changelogs/changelog.yaml, galaxy.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/737
the comment was already fixed in another PR but not released
=> Release 3.6.1 commit

.azure-pipelines/azure-pipelines.yml, README.md, tests/sanity/ignore-2.19.txt
Add stable-2.18 to CI, fix README
=> Add stable-2.18 to CI, fix README

changelogs/fragments/0-pg_set.yml, plugins/modules/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
Relates to https://github.com/ansible-collections/community.postgresql/issues/744
- Feature pull request
postgresql_set
=> postgresql_set: add queries ret val to help debug

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-pg_set.yml, changelogs/fragments/1-pg_set.yml, galaxy.yml
=> Release 3.7.0 commit

plugins/modules/postgresql_set.py, tests/integration/targets/postgresql_set/tasks/postgresql_set_initial.yml
postgresql_set: refactoring
No changelog fragment needed.
=> postgresql_set: refactoring

plugins/modules/postgresql_info.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/754
=> postgresql_info return values doc section: leave only top level keys info

plugins/modules/postgresql_db.py
Just refactoring
I shouldn't have probably touched it.. but it looked so confusing.
If you think it's unnecessary risk, just say, we could close it.
- the db_create function was split. no logic changes
- in main:
- I removed/moved exceptions to the end of the logical block
- It causes indentation changes that look spooky
=> postgresql_db: split db_create function, simplify exception handling

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_user.yml, changelogs/fragments/420-pg_hba-fix-hash-symbol-in-quotes.yml, changelogs/fragments/705-pg_hba-invalid-and-parsing.yml, changelogs/fragments/730-insufficient-key-in-pg_hba-rule.yml, changelogs/fragments/763-add-publication-with-specific-columns.yml, galaxy.yml
=> Release 3.8.0 commit

.pre-commit-config.yaml
Disable the `isort` pre-commit as per @Andersson007 in #768 
closes #768
=> style(pre-commit): comment out the 'isort' pre-commit as per @andersson007 ; closes #768

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/772-refactoring-pg_hba-module.yml, galaxy.yml
=> Release 3.9.0 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/779-fix-address.yaml, galaxy.yml
=> Release 3.9.1 commit

plugins/modules/postgresql_ping.py, plugins/modules/postgresql_set.py, plugins/modules/postgresql_user.py
=> Fix linting issues

README.md
Make it clear that this collection does not install the database.
=> Add note that this collection does not support installing PostgreSQL

.azure-pipelines/azure-pipelines.yml, README.md
AZP: update matrix; README: update
Remove testing against EOL stable-2.15
=> AZP: update matrix; README: update

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_query.yml, changelogs/fragments/783-fix-postgresql-privs-not-specified-schema.yml, changelogs/fragments/788-fix-postresql-info-db-connection.yml, galaxy.yml
=> Release 3.10.0 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_info.yml, galaxy.yml
=> Release 3.10.1 commit

changelogs/fragments/0-postgresql_info.yml, plugins/modules/postgresql_info.py, tests/integration/targets/postgresql_info/tasks/postgresql_info_initial.yml
Reproduced, see the test case I added
Fixes https://github.com/ansible-collections/community.postgresql/issues/794
=> postgresql_info: fix failure when db/login_db are not specified

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql_info.yml, galaxy.yml
=> Release 3.10.2 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-postgresql-user.yml, changelogs/fragments/0-postgresql_info.yml, changelogs/fragments/778-pg-hba-improvements.yml, changelogs/fragments/802-unquoted-config-values.yml, galaxy.yml
=> Release 3.11.0 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/813-postgresql_publication-rowfilter.yml, galaxy.yml
=> Release 3.12.0 commit

plugins/modules/postgresql_set.py
postgresql_set: add a ref to postgresql_alter_system
Relates to https://github.com/ansible-collections/community.postgresql/pull/816
=> postgresql_set: add a ref to postgresql_alter_system

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/818-table-consider-schema-name.yaml, galaxy.yml
=> Release 3.13.0 commit

plugins/modules/postgresql_table.py
Found column changes were being silently ignored returning "ok" each time. Reviewed the code and found there's no handling of altered columns. Added a note to make that clear.
`module: postgresql_table`
=> Add note that column changes on an existing table are ignored

changelogs/fragments/5-python2.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/829
=> Announce Python 3 acceptance; stop testing against Python 2

changelogs/fragments/2-privs.yml, plugins/modules/postgresql_privs.py
Fixes https://github.com/ansible-collections/community.postgresql/issues/408
=> postgresql_privs: remove deprecated password option

changelogs/fragments/1-remove_privs.yml, plugins/modules/postgresql_user.py, tests/integration/targets/postgresql_user/tasks/postgresql_user_general.yml, tests/integration/targets/postgresql_user/tasks/postgresql_user_initial.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/493
=> postgresql_user: remove priv option

README.md
=> README: update versions info

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/0-alter_system.yml, galaxy.yml
=> Release 4.0.1 commit

CHANGELOG.rst, changelogs/changelog.yaml, changelogs/fragments/858-negated-change-report.yml, galaxy.yml
=> Release 3.14.2 commit

changelogs/fragments/879-fix-conn-limit-zero.yml, plugins/modules/postgresql_db.py, tests/integration/targets/postgresql_db/tasks/main.yml, tests/integration/targets/postgresql_db/tasks/postgresql_db_conn_limit_zero.yml
Fixes https://github.com/ansible-collections/community.postgresql/issues/879
=> postgresql_db: fix conn_limit 0 bug
